CREATE TABLE asu_bdy_boundaryhighwatermark (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	boundarytype nvarchar(50) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_ceremonialcounty (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_country (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_devolvedparliamentconstituency (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	boundaryparentreference_id uniqueidentifier not null,
	boundaryparentreference_featuretype nvarchar(50) not null,
	boundaryparentreference_classification nvarchar(50) not null,
	boundaryparentreference_name1_text nvarchar(254) not null,
	boundaryparentreference_name1_language nvarchar(3),
	boundaryparentreference_name2_text nvarchar(254),
	boundaryparentreference_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_devolvedparliamentelectoralregion (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_electoraldivision (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	boundaryparentreference1_id uniqueidentifier not null,
	boundaryparentreference1_featuretype nvarchar(50) not null,
	boundaryparentreference1_classification nvarchar(50) not null,
	boundaryparentreference1_name1_text nvarchar(254) not null,
	boundaryparentreference1_name1_language nvarchar(3),
	boundaryparentreference1_name2_text nvarchar(254),
	boundaryparentreference1_name2_language nvarchar(3),
	boundaryparentreference2_id uniqueidentifier,
	boundaryparentreference2_featuretype nvarchar(50),
	boundaryparentreference2_classification nvarchar(50),
	boundaryparentreference2_name1_text nvarchar(254),
	boundaryparentreference2_name1_language nvarchar(3),
	boundaryparentreference2_name2_text nvarchar(254),
	boundaryparentreference2_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	hasdetachedpart boolean not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_glaassemblyconstituency (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	boundaryparentreference_id uniqueidentifier not null,
	boundaryparentreference_featuretype nvarchar(50) not null,
	boundaryparentreference_classification nvarchar(50) not null,
	boundaryparentreference_name1_text nvarchar(254) not null,
	boundaryparentreference_name1_language nvarchar(3),
	boundaryparentreference_name2_text nvarchar(254),
	boundaryparentreference_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_historiccounty (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_historiceuropeanregion (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_lowertierlocalauthority (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	boundaryparentreference_id uniqueidentifier,
	boundaryparentreference_featuretype nvarchar(50),
	boundaryparentreference_classification nvarchar(50),
	boundaryparentreference_name1_text nvarchar(254),
	boundaryparentreference_name1_language nvarchar(3),
	boundaryparentreference_name2_text nvarchar(254),
	boundaryparentreference_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	isborough boolean not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_parishorcommunity (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	boundaryparentreference1_id uniqueidentifier not null,
	boundaryparentreference1_featuretype nvarchar(50) not null,
	boundaryparentreference1_classification nvarchar(50) not null,
	boundaryparentreference1_name1_text nvarchar(254) not null,
	boundaryparentreference1_name1_language nvarchar(3),
	boundaryparentreference1_name2_text nvarchar(254),
	boundaryparentreference1_name2_language nvarchar(3),
	boundaryparentreference2_id uniqueidentifier,
	boundaryparentreference2_featuretype nvarchar(50),
	boundaryparentreference2_classification nvarchar(50),
	boundaryparentreference2_name1_text nvarchar(254),
	boundaryparentreference2_name1_language nvarchar(3),
	boundaryparentreference2_name2_text nvarchar(254),
	boundaryparentreference2_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	hassharedarea boolean not null,
	hasdetachedpart boolean not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_pollingdistrict (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	pollingdistrictid nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	boundaryparentreference1_id uniqueidentifier not null,
	boundaryparentreference1_featuretype nvarchar(50) not null,
	boundaryparentreference1_classification nvarchar(50) not null,
	boundaryparentreference1_name1_text nvarchar(254) not null,
	boundaryparentreference1_name1_language nvarchar(3),
	boundaryparentreference1_name2_text nvarchar(254),
	boundaryparentreference1_name2_language nvarchar(3),
	boundaryparentreference2_id uniqueidentifier not null,
	boundaryparentreference2_featuretype nvarchar(50) not null,
	boundaryparentreference2_classification nvarchar(50) not null,
	boundaryparentreference2_name1_text nvarchar(254) not null,
	boundaryparentreference2_name1_language nvarchar(3),
	boundaryparentreference2_name2_text nvarchar(254),
	boundaryparentreference2_name2_language nvarchar(3),
	boundaryparentreference3_id uniqueidentifier not null,
	boundaryparentreference3_featuretype nvarchar(50) not null,
	boundaryparentreference3_classification nvarchar(50) not null,
	boundaryparentreference3_name1_text nvarchar(254) not null,
	boundaryparentreference3_name1_language nvarchar(3),
	boundaryparentreference3_name2_text nvarchar(254),
	boundaryparentreference3_name2_language nvarchar(3),
	boundaryparentreference4_id uniqueidentifier,
	boundaryparentreference4_featuretype nvarchar(50),
	boundaryparentreference4_classification nvarchar(50),
	boundaryparentreference4_name1_text nvarchar(254),
	boundaryparentreference4_name1_language nvarchar(3),
	boundaryparentreference4_name2_text nvarchar(254),
	boundaryparentreference4_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_region (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_regionalauthority (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_uppertierlocalauthority (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	isborough boolean not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_ward (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10),
	boundarytype nvarchar(50) not null,
	boundaryparentreference1_id uniqueidentifier not null,
	boundaryparentreference1_featuretype nvarchar(50) not null,
	boundaryparentreference1_classification nvarchar(50) not null,
	boundaryparentreference1_name1_text nvarchar(254) not null,
	boundaryparentreference1_name1_language nvarchar(3),
	boundaryparentreference1_name2_text nvarchar(254),
	boundaryparentreference1_name2_language nvarchar(3),
	boundaryparentreference2_id uniqueidentifier,
	boundaryparentreference2_featuretype nvarchar(50),
	boundaryparentreference2_classification nvarchar(50),
	boundaryparentreference2_name1_text nvarchar(254),
	boundaryparentreference2_name1_language nvarchar(3),
	boundaryparentreference2_name2_text nvarchar(254),
	boundaryparentreference2_name2_language nvarchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	hasdetachedpart boolean not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_westminsterconstituency (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	gsscode nvarchar(10) not null,
	boundarytype nvarchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
