CREATE TABLE bld_fts_buildingline (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	isobscured boolean not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE bld_fts_buildingpart (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	oslandcovertiera nvarchar(15) not null,
	oslandcovertierb nvarchar(20) not null,
	oslandcover_evidencedate date,
	oslandcover_updatedate date not null,
	oslandcover_source nvarchar(50),
	oslandusetiera nvarchar(50) not null,
	oslandusetierb nvarchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date not null,
	oslanduse_source nvarchar(50),
	absoluteheightroofbase numeric(6,2),
	relativeheightroofbase numeric(6,2),
	absoluteheightmaximum numeric(6,2),
	relativeheightmaximum numeric(6,2),
	absoluteheightminimum numeric(6,2),
	heightconfidencelevel nvarchar(15),
	height_evidencedate date,
	height_updatedate date,
	height_source nvarchar(50),
	associatedstructure nvarchar(25),
	isobscured boolean not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
