CREATE TABLE str_fts_compoundstructure (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	description nvarchar(25) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name1_source nvarchar(50),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source nvarchar(50),
	name3_text nvarchar(254),
	name3_language nvarchar(3),
	name3_evidencedate date,
	name3_updatedate date,
	name3_source nvarchar(50),
	name4_text nvarchar(254),
	name4_language nvarchar(3),
	name4_evidencedate date,
	name4_updatedate date,
	name4_source nvarchar(50),
	operationalstatus nvarchar(10) not null,
	capturespecification nvarchar(10) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structure (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	oslandcovertiera nvarchar(15),
	oslandcovertierb nvarchar(92),
	oslandcover_evidencedate date,
	oslandcover_updatedate date,
	oslandcover_source nvarchar(50),
	oslandusetiera nvarchar(50),
	oslandusetierb nvarchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date,
	oslanduse_source nvarchar(50),
	absoluteheightroofbase numeric(6,2),
	relativeheightroofbase numeric(6,2),
	absoluteheightmaximum numeric(6,2),
	relativeheightmaximum numeric(6,2),
	absoluteheightminimum numeric(6,2),
	heightconfidencelevel nvarchar(15),
	height_evidencedate date,
	height_updatedate date,
	height_source nvarchar(50),
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name1_source nvarchar(50),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source nvarchar(50),
	istidal boolean not null,
	ishistoric boolean not null,
	associatedstructure nvarchar(25),
	operationalstatus nvarchar(10),
	isobscured boolean not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structureline (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	istidal boolean not null,
	ishistoric boolean not null,
	operationalstatus nvarchar(10),
	isobscured boolean not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structurepoint (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name1_source nvarchar(50),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source nvarchar(50),
	ishistoric boolean not null,
	operationalstatus nvarchar(10),
	isobscured boolean not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
