CREATE TABLE trn_rami_highwaydedication (
	osid uniqueidentifier not null,
	authorityid nvarchar(25) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(35) not null,
	publicrightofway boolean not null,
	nationalcycleroute boolean not null,
	quietroute boolean,
	obstruction boolean not null,
	planningorder boolean,
	worksprohibited boolean,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_highwaydedication_hwydedntwkref (
	networkreferenceid uniqueidentifier,
	networkfeaturetype nvarchar(9),
	highwaydedicationid uniqueidentifier,
	highwaydedicationversiondate date,
	PRIMARY KEY (networkreferenceid,highwaydedicationid,highwaydedicationversiondate)
);
CREATE TABLE trn_rami_maintenancearea (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	maintenanceresponsibility nvarchar(60) not null,
	maintenanceauthority_identifier nvarchar(4),
	maintenanceauthority_authorityname nvarchar(100),
	highwayauthority_identifier nvarchar(4) not null,
	highwayauthority_authorityname nvarchar(100) not null,
	locationdescription nvarchar(250),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_maintenanceline (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	maintenanceresponsibility nvarchar(60) not null,
	maintenanceauthority_identifier nvarchar(4),
	maintenanceauthority_authorityname nvarchar(100),
	highwayauthority_identifier nvarchar(4) not null,
	highwayauthority_authorityname nvarchar(100) not null,
	locationdescription nvarchar(250),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_maintenancepoint (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	maintenanceresponsibility nvarchar(60) not null,
	maintenanceauthority_identifier nvarchar(4),
	maintenanceauthority_authorityname nvarchar(100),
	highwayauthority_identifier nvarchar(4) not null,
	highwayauthority_authorityname nvarchar(100) not null,
	locationdescription nvarchar(250),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementarea (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	reinstatementtype nvarchar(60) not null,
	locationdescription nvarchar(250),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementline (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	reinstatementtype nvarchar(60) not null,
	locationdescription nvarchar(250),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementpoint (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	reinstatementtype nvarchar(60) not null,
	locationdescription nvarchar(250),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(24) not null,
	restriction nvarchar(26) not null,
	trafficsign1 nvarchar(120),
	trafficsign2 nvarchar(120),
	"structure" nvarchar(40),
	inclusion nvarchar(1209),
	exemption nvarchar(1209),
	timeinterval nvarchar(254),
	measure1_value numeric(6,1),
	measure1_unitofmeasure nvarchar(4),
	measure1_sourceofmeasure nvarchar(10),
	measure2_value numeric(6,1),
	measure2_unitofmeasure nvarchar(4),
	measure2_sourceofmeasure nvarchar(10),
	atpositionxcoordinate numeric(10,3),
	atpositionycoordinate numeric(10,3),
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction_datetimequal (
	datetimequalifierid uniqueidentifier,
	restrictionid uniqueidentifier,
	restrictionversiondate date,
	nameddate nvarchar(9),
	startdate date,
	enddate date,
	startmonthday nvarchar(6),
	endmonthday nvarchar(6),
	namedtime nvarchar(17),
	starttime nvarchar(8),
	endtime nvarchar(8),
	namedperiod nvarchar(28),
	namedday nvarchar(15),
	PRIMARY KEY (datetimequalifierid,restrictionversiondate)
);
CREATE TABLE trn_rami_restriction_restrictntwkref (
	networkreferenceid uniqueidentifier,
	networkfeaturetype nvarchar(9),
	roadlinkdirection nvarchar(21),
	roadlinksequence integer,
	restrictionid uniqueidentifier,
	restrictionversiondate date,
	PRIMARY KEY (networkreferenceid,restrictionid,restrictionversiondate)
);
CREATE TABLE trn_rami_routinghazard (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(12) not null,
	hazarddescription nvarchar(50),
	atpositionxcoordinate numeric(10,3),
	atpositionycoordinate numeric(10,3),
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_routinghazard_routhazntwkref (
	networkreferenceid uniqueidentifier,
	networkfeaturetype nvarchar(9),
	routinghazardid uniqueidentifier,
	routinghazardversiondate date,
	PRIMARY KEY (networkreferenceid,routinghazardid,routinghazardversiondate)
);
CREATE TABLE trn_rami_routingstructure (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(40) not null,
	structuredescription nvarchar(50),
	atpositionxcoordinate numeric(10,3),
	atpositionycoordinate numeric(10,3),
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_routingstructure_routstructntwkref (
	networkreferenceid uniqueidentifier,
	networkfeaturetype nvarchar(9),
	routingstructureid uniqueidentifier,
	routingstructureversiondate date,
	PRIMARY KEY (networkreferenceid,routingstructureid,routingstructureversiondate)
);
CREATE TABLE trn_rami_specialdesignationarea (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	designation nvarchar(70) not null,
	designationdescription nvarchar(254),
	locationdescription nvarchar(250),
	timeinterval nvarchar(254),
	contactauthority_identifier nvarchar(4),
	contactauthority_authorityname nvarchar(100),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationarea_datetimequal (
	datetimequalifierid uniqueidentifier,
	specialdesignationid uniqueidentifier,
	specialdesignationversiondate date,
	nameddate nvarchar(9),
	startdate date,
	enddate date,
	startmonthday nvarchar(6),
	endmonthday nvarchar(6),
	namedtime nvarchar(17),
	starttime nvarchar(8),
	endtime nvarchar(8),
	namedperiod nvarchar(28),
	namedday nvarchar(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
CREATE TABLE trn_rami_specialdesignationline (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	geometry_length numeric(15,6) not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	designation nvarchar(70) not null,
	designationdescription nvarchar(254),
	locationdescription nvarchar(250),
	timeinterval nvarchar(254),
	contactauthority_identifier nvarchar(4),
	contactauthority_authorityname nvarchar(100),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationline_datetimequal (
	datetimequalifierid uniqueidentifier,
	specialdesignationid uniqueidentifier,
	specialdesignationversiondate date,
	nameddate nvarchar(9),
	startdate date,
	enddate date,
	startmonthday nvarchar(6),
	endmonthday nvarchar(6),
	namedtime nvarchar(17),
	starttime nvarchar(8),
	endtime nvarchar(8),
	namedperiod nvarchar(28),
	namedday nvarchar(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
CREATE TABLE trn_rami_specialdesignationpoint (
	osid uniqueidentifier not null,
	authorityid nvarchar(17) not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry not null,
	theme nvarchar(40) not null,
	description nvarchar(20) not null,
	designation nvarchar(70) not null,
	designationdescription nvarchar(254),
	locationdescription nvarchar(250),
	timeinterval nvarchar(254),
	contactauthority_identifier nvarchar(4),
	contactauthority_authorityname nvarchar(100),
	partialreference boolean not null,
	usrn integer not null,
	mssql_geom as geometry::STGeomFromText(geometry, 27700) persisted,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationpoint_datetimequal (
	datetimequalifierid uniqueidentifier,
	specialdesignationid uniqueidentifier,
	specialdesignationversiondate date,
	nameddate nvarchar(9),
	startdate date,
	enddate date,
	startmonthday nvarchar(6),
	endmonthday nvarchar(6),
	namedtime nvarchar(17),
	starttime nvarchar(8),
	endtime nvarchar(8),
	namedperiod nvarchar(28),
	namedday nvarchar(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
