/* This DDL is based on data schema version 1.0 */
CREATE TABLE add_isl_royalmailaddress (
	udprn integer not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	organisationname nvarchar(60),
	departmentname nvarchar(60),
	subbuildingname nvarchar(30),
	buildingname nvarchar(50),
	buildingnumber integer,
	dependentthoroughfare nvarchar(80),
	thoroughfare nvarchar(80),
	doubledependentlocality nvarchar(35),
	dependentlocality nvarchar(35),
	posttown nvarchar(30) not null,
	postcode nvarchar(8) not null,
	postcodetype nvarchar(10) not null,
	deliverypointsuffix nvarchar(2) not null,
	welshdependentthoroughfare nvarchar(80),
	welshthoroughfare nvarchar(80),
	welshdoubledependentlocality nvarchar(35),
	welshdependentlocality nvarchar(35),
	welshposttown nvarchar(30),
	poboxnumber nvarchar(13),
	updatedate date not null,
	entrydate date not null,
	easting numeric(8,2),
	northing numeric(9,2),
	latitude numeric(9,7) not null,
	longitude numeric(9,7) not null,
	geometry geometry not null,
	positionalaccuracy nvarchar(25) not null,
	geometryallocationmethod nvarchar(25) not null,
	unmatchedreason nvarchar(100),
	unmatchedreasondate date,
	uprn bigint,
	matchedaddressfeaturetype nvarchar(25),
	matchtype nvarchar(20) not null,
	matchdate date,
	matchmethod nvarchar(10),
	matchingorganisation nvarchar(25),
	PRIMARY KEY (udprn)
);
