/* This DDL is based on data schema version 3.0 */
CREATE TABLE add_isl_nonaddressableobject (
	uprn bigint not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	organisationname nvarchar(100),
	poboxnumber nvarchar(13),
	subname nvarchar(500),
	name nvarchar(110),
	"number" nvarchar(13),
	streetname nvarchar(100) not null,
	locality nvarchar(35),
	townname nvarchar(35),
	islandname nvarchar(50),
	postcode nvarchar(8) not null,
	fulladdress nvarchar(1000) not null,
	country nvarchar(16) not null,
	alternatelanguagesubname nvarchar(500),
	alternatelanguagename nvarchar(110),
	alternatelanguagenumber nvarchar(13),
	alternatelanguagestreetname nvarchar(100),
	alternatelanguagelocality nvarchar(35),
	alternatelanguagetownname nvarchar(35),
	alternatelanguageislandname nvarchar(50),
	alternatelanguage nvarchar(3),
	alternatelanguagefulladdress nvarchar(1000),
	floorlevel nvarchar(30),
	lowestfloorlevel numeric(3,1),
	highestfloorlevel numeric(3,1),
	classificationcode nvarchar(6) not null,
	classificationdescription nvarchar(230) not null,
	primaryclassificationdescription nvarchar(120) not null,
	secondaryclassificationdescription nvarchar(120),
	tertiaryclassificationdescription nvarchar(120),
	quaternaryclassificationdescription nvarchar(120),
	buildstatus nvarchar(18) not null,
	buildstatusdate date,
	addressstatus nvarchar(11) not null,
	postcodesource nvarchar(148) not null,
	parentuprn bigint,
	rootuprn bigint,
	hierarchylevel integer not null,
	usrn integer not null,
	usrnmatchindicator nvarchar(17) not null,
	localcustodiancode integer not null,
	localcustodiandescription nvarchar(35) not null,
	lowertierlocalauthoritygsscode nvarchar(9),
	easting numeric(8,2),
	northing numeric(9,2),
	latitude numeric(9,7) not null,
	longitude numeric(9,7) not null,
	geometry geometry not null,
	positionalaccuracy nvarchar(25) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	PRIMARY KEY (uprn)
);
CREATE TABLE add_isl_nonaddressableobject_altadd (
	alternateaddressid uniqueidentifier not null,
	uprn bigint not null,
	featuretypeversiondate date not null,
	usrn integer not null,
	addressstatus nvarchar(11) not null,
	alternatesubname nvarchar(500),
	alternatename nvarchar(110),
	alternatenumber nvarchar(13),
	streetname nvarchar(100) not null,
	locality nvarchar(35),
	townname nvarchar(35),
	islandname nvarchar(50),
	"language" nvarchar(3) not null,
	postcode nvarchar(8) not null,
	fulladdress nvarchar(500) not null,
	floorlevel nvarchar(30),
	lowestfloorlevel numeric(3,1),
	highestfloorlevel numeric(3,1),
	updatedate date not null,
	effectivestartdate date not null,
	effectiveenddate date,
	PRIMARY KEY (alternateaddressid,featuretypeversiondate)
);
CREATE TABLE add_isl_nonaddressableobject_rltenty (
	relatedentityid uniqueidentifier not null,
	uprn bigint not null,
	featuretypeversiondate date not null,
	crossreferencefeature nvarchar(40) not null,
	crossreferenceid nvarchar(36) not null,
	relationshiptype nvarchar(30),
	"source" nvarchar(110) not null,
	updatedate date not null,
	effectivestartdate date,
	effectiveenddate date,
	PRIMARY KEY (relatedentityid,featuretypeversiondate)
);
CREATE TABLE add_isl_nonaddressableobject_otrclass (
	otherclassificationid uniqueidentifier not null,
	uprn bigint not null,
	featuretypeversiondate date not null,
	classificationcode nvarchar(6) not null,
	classificationdescription nvarchar(230),
	classificationscheme nvarchar(60),
	schemeversion numeric(2,1),
	updatedate date not null,
	PRIMARY KEY (otherclassificationid,featuretypeversiondate)
);
