/* This DDL is based on data schema version 1.0 */
CREATE TABLE add_isl_streetaddress (
	usrn integer not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	streettype nvarchar(33) not null,
	classification nvarchar(26),
	operationalstate nvarchar(18),
	operationalstatedate date,
	streetname nvarchar(100) not null,
	locality nvarchar(35),
	townname nvarchar(35),
	administrativearea nvarchar(35) not null,
	country nvarchar(16) not null,
	alternatelanguagestreetname nvarchar(110),
	alternatelanguagelocality nvarchar(110),
	alternatelanguagetownname nvarchar(35),
	alternatelanguageadministrativearea nvarchar(35),
	alternatelanguage nvarchar(3),
	snnauthoritycode nvarchar(4) not null,
	snnauthoritydescription nvarchar(35) not null,
	surfacematerial nvarchar(10),
	starteasting numeric(8,2),
	startnorthing numeric(9,2),
	endeasting numeric(8,2),
	endnorthing numeric(9,2),
	startlatitude numeric(9,7) not null,
	startlongitude numeric(9,7) not null,
	endlatitude numeric(9,7) not null,
	endlongitude numeric(9,7) not null,
	geometry geometry not null,
	streettolerance integer not null,
	effectivestartdate date not null,
	effectiveenddate date,
	PRIMARY KEY (usrn)
);
