/* This DDL is based on data schema version 1.0 */
CREATE TABLE gnm_fts_namedarea (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	descriptiongroup nvarchar(25) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	extentdefinition nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date not null,
	name1_source nvarchar(50),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source nvarchar(50),
	name3_text nvarchar(254),
	name3_language nvarchar(3),
	name3_evidencedate date,
	name3_updatedate date,
	name3_source nvarchar(50),
	name4_text nvarchar(254),
	name4_language nvarchar(3),
	name4_evidencedate date,
	name4_updatedate date,
	name4_source nvarchar(50),
	sameasdbpedia nvarchar(100),
	sameasgeonames nvarchar(100),
	sameasdbobih integer,
	height numeric(6,2),
	PRIMARY KEY (osid)
);
