CREATE TABLE gnm_fts_namedarea (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(18,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	descriptiongroup nvarchar(25) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	extentdefinition nvarchar(50) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date not null,
	name1_source nvarchar(50),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source nvarchar(50),
	name3_text nvarchar(254),
	name3_language nvarchar(3),
	name3_evidencedate date,
	name3_updatedate date,
	name3_source nvarchar(50),
	name4_text nvarchar(254),
	name4_language nvarchar(3),
	name4_evidencedate date,
	name4_updatedate date,
	name4_source nvarchar(50),
	sameasdbpedia nvarchar(100),
	sameasgeonames nvarchar(100),
	sameasdbobih integer,
	height numeric(6,2),
	PRIMARY KEY (osid)
);
CREATE TABLE gnm_fts_namedpoint (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	descriptiongroup nvarchar(25) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name3_text nvarchar(254),
	name3_language nvarchar(3),
	name4_text nvarchar(254),
	name4_language nvarchar(3),
	boundedbyminx numeric(10,3) not null,
	boundedbyminy numeric(10,3) not null,
	boundedbymaxx numeric(10,3) not null,
	boundedbymaxy numeric(10,3) not null,
	lowertierlocalauthoritygsscode nvarchar(10),
	lowertierlocalauthority_name1_text nvarchar(254),
	lowertierlocalauthority_name1_language nvarchar(3),
	lowertierlocalauthority_name2_text nvarchar(254),
	lowertierlocalauthority_name2_language nvarchar(3),
	uppertierlocalauthoritygsscode nvarchar(10),
	uppertierlocalauthority_name1_text nvarchar(254),
	uppertierlocalauthority_name1_language nvarchar(3),
	uppertierlocalauthority_name2_text nvarchar(254),
	uppertierlocalauthority_name2_language nvarchar(3),
	regionalauthoritygsscode nvarchar(10),
	regionalauthority_name1_text nvarchar(254),
	regionalauthority_name1_language nvarchar(3),
	regionalauthority_name2_text nvarchar(254),
	regionalauthority_name2_language nvarchar(3),
	regiongsscode nvarchar(10),
	region_name1_text nvarchar(254),
	region_name1_language nvarchar(3),
	region_name2_text nvarchar(254),
	region_name2_language nvarchar(3),
	countrygsscode nvarchar(10),
	country_name1_text nvarchar(254),
	country_name1_language nvarchar(3),
	country_name2_text nvarchar(254),
	country_name2_language nvarchar(3),
	sameasdbpedia nvarchar(100),
	sameasgeonames nvarchar(100),
	sameasdbobih integer,
	height numeric(6,2),
	PRIMARY KEY (osid)
);
