/* This DDL is based on data schema version 1.0 */
CREATE TABLE lus_fts_site (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source nvarchar(50),
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source nvarchar(50),
	oslandusetiera nvarchar(50) not null,
	oslandusetierb nvarchar(166),
	oslanduse_evidencedate date,
	oslanduse_updatedate date not null,
	oslanduse_source nvarchar(50),
	stakeholder nvarchar(99),
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name1_source nvarchar(50),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source nvarchar(50),
	primaryuprn bigint,
	extentdefinition nvarchar(30) not null,
	PRIMARY KEY (osid)
);
