/* This DDL is based on data schema version 2.0 */
CREATE TABLE str_fts_structure (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area_m2 numeric(15,3),
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_capturemethod nvarchar(25),
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_capturemethod nvarchar(25),
	oslandcovertiera nvarchar(15),
	oslandcovertierb nvarchar(92),
	oslandcover_evidencedate date,
	oslandcover_updatedate date,
	oslandcover_capturemethod nvarchar(25),
	oslandusetiera nvarchar(50),
	oslandusetierb nvarchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date,
	oslanduse_capturemethod nvarchar(25),
	absoluteheightroofbase numeric(6,2),
	relativeheightroofbase numeric(6,2),
	absoluteheightmaximum numeric(6,2),
	relativeheightmaximum numeric(6,2),
	absoluteheightminimum numeric(6,2),
	heightconfidencelevel nvarchar(15),
	height_evidencedate date,
	height_updatedate date,
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	istidal BIT not null,
	ishistoric BIT not null,
	associatedstructure nvarchar(25),
	operationalstatus nvarchar(10),
	isobscured BIT not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structure_habcovref (
	osid uniqueidentifier not null,
	scheme nvarchar(20),
	habitatcode nvarchar(5),
	habitatdescription nvarchar(80),
	percentage integer,
	percentage_evidencedate date,
	percentage_updatedate date,
	featuretypeversiondate date,
	PRIMARY KEY (osid,featuretypeversiondate,habitatdescription)
);
