/* This DDL is based on data schema version 3.0 */
CREATE TABLE str_fts_structure (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	firstdigitalcapturedate date,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area_m2 numeric(15,3) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_capturemethod nvarchar(25) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_capturemethod nvarchar(25) not null,
	oslandcovertiera nvarchar(15),
	oslandcovertierb nvarchar(92) not null,
	oslandcover_evidencedate date,
	oslandcover_updatedate date,
	oslandcover_capturemethod nvarchar(25),
	oslandusetiera nvarchar(50),
	oslandusetierb nvarchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date,
	oslanduse_capturemethod nvarchar(25),
	height_absoluteroofbase_m numeric(5,1),
	height_relativeroofbase_m numeric(4,1),
	height_absolutemax_m numeric(5,1),
	height_relativemax_m numeric(4,1),
	height_absolutemin_m numeric(5,1),
	height_confidencelevel nvarchar(15),
	height_evidencedate date,
	height_updatedate date,
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	istidal BIT not null,
	ishistoric BIT not null,
	associatedstructure nvarchar(25),
	isobscured BIT not null,
	physicallevel nvarchar(15) not null,
	capturespecification nvarchar(10) not null,
	containingsitecount integer,
	smallestsite_siteid uniqueidentifier,
	smallestsite_landusetiera nvarchar(50),
	smallestsite_landusetierb nvarchar(88) not null,
	largestsite_landusetiera nvarchar(50),
	largestsite_landusetierb nvarchar(88) not null,
	nlud_code nvarchar(4),
	nlud_orderdescription nvarchar(30),
	nlud_groupdescription nvarchar(40),
	address_classificationcode nvarchar(2),
	address_primarydescription nvarchar(120),
	address_secondarydescription nvarchar(120),
	lowertierlocalauthority_gsscode nvarchar(10),
	lowertierlocalauthority_count integer,
	status nvarchar(10),
	status_updatedate date,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structure_habcovref (
	osid uniqueidentifier not null,
	scheme nvarchar(20) not null,
	habitatcode nvarchar(5),
	habitatdescription nvarchar(80) not null,
	percentage integer,
	percentage_evidencedate date,
	percentage_updatedate date,
	featuretypeversiondate date not null,
	PRIMARY KEY (osid,featuretypeversiondate,habitatdescription)
);
CREATE TABLE str_fts_structure_siteref (
	siteid uniqueidentifier not null,
	structureid uniqueidentifier not null,
	structureversiondate date not null,
	PRIMARY KEY (siteid,structureid,structureversiondate)
);
