/* This DDL is based on data schema version 1.0 */
CREATE TABLE trn_ntwk_railwaylink (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length_m numeric(15,3) not null,
	theme nvarchar(40) not null,
	description nvarchar(50) not null,
	gauge nvarchar(15),
	"structure" nvarchar(15),
	physicallevel nvarchar(15),
	railwayuse nvarchar(25),
	trackrepresentation nvarchar(15),
	direction nvarchar(21),
	operationalstatus nvarchar(10) not null,
	inferred BIT not null,
	name1_text nvarchar(254),
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	localname1_text nvarchar(254),
	localname1_language nvarchar(3),
	localname2_text nvarchar(254),
	localname2_language nvarchar(3),
	startnode uniqueidentifier not null,
	endnode uniqueidentifier not null,
	PRIMARY KEY (osid)
);
