/* This DDL is based on data schema version 1.0 */
CREATE TABLE trn_ntwk_cyclelane (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length_m numeric(15,3) not null,
	geometry_evidencedate date not null,
	geometry_updatedate date not null,
	geometry_capturemethod nvarchar(25) not null,
	theme nvarchar(40) not null,
	description nvarchar(40) not null,
	parentid uniqueidentifier not null,
	sideoflink nvarchar(10),
	cyclelaneinfo_minimumwidth_m numeric(3,1) not null,
	cyclelaneinfo_modalwidth_m numeric(3,1) not null,
	cyclelaneinfo_direction nvarchar(21) not null,
	cyclelaneinfo_evidencedate date not null,
	cyclelaneinfo_updatedate date not null,
	cyclelaneinfo_capturemethod nvarchar(25) not null,
	linkid uniqueidentifier,
	linkid_featuretype nvarchar(10),
	linkid_confidence nvarchar(30) not null,
	linkid_evidencedate date not null,
	linkid_updatedate date not null,
	linkid_capturemethod nvarchar(25) not null,
	PRIMARY KEY (osid)
);
