/* This DDL is based on data schema version 1.0 */
CREATE TABLE trn_ntwk_buslane (
	osid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length_m numeric(15,3) not null,
	geometry_evidencedate date not null,
	geometry_updatedate date not null,
	geometry_capturemethod nvarchar(25) not null,
	theme nvarchar(40) not null,
	description nvarchar(40) not null,
	parentid uniqueidentifier not null,
	sideofroad nvarchar(10),
	buslaneinfo_minimumwidth_m numeric(3,1) not null,
	buslaneinfo_modalwidth_m numeric(3,1) not null,
	buslaneinfo_direction nvarchar(21) not null,
	buslaneinfo_evidencedate date not null,
	buslaneinfo_updatedate date not null,
	buslaneinfo_capturemethod nvarchar(25) not null,
	linkid uniqueidentifier,
	linkid_featuretype nvarchar(10),
	linkid_confidence nvarchar(30) not null,
	linkid_evidencedate date not null,
	linkid_updatedate date not null,
	linkid_capturemethod nvarchar(25) not null,
	PRIMARY KEY (osid)
);
