/* This DDL is based on data schema version 3.0 */
CREATE TABLE trn_ntwk_pathlink (
	osid uniqueidentifier not null,
	toid nvarchar(20),
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_length_m numeric(15,3) not null,
	theme nvarchar(40) not null,
	description nvarchar(42) not null,
	pathname1_text nvarchar(254),
	pathname1_language nvarchar(3),
	pathname2_text nvarchar(254),
	pathname2_language nvarchar(3),
	alternatename1_text nvarchar(254),
	alternatename1_language nvarchar(3),
	alternatename2_text nvarchar(254),
	alternatename2_language nvarchar(3),
	surfacetype nvarchar(13),
	elevationgain_indirection numeric(6,1) not null,
	elevationgain_againstdirection numeric(6,1) not null,
	heightingmethod nvarchar(19) not null,
	capturespecification nvarchar(10) not null,
	matchstatus nvarchar(39) not null,
	startnode uniqueidentifier not null,
	startgradeseparation integer not null,
	endnode uniqueidentifier not null,
	endgradeseparation integer not null,
	presenceofstreetlight_coverage nvarchar(15) not null,
	presenceofstreetlight_evidencedate date not null,
	presenceofstreetlight_updatedate date not null,
	presenceofstreetlight_capturemethod nvarchar(25) not null,
	presenceofcyclelane_overall_m numeric(6,2) not null,
	presenceofcyclelane_overallpercentage integer not null,
	presenceofcyclelane_indirection_m numeric(6,2) not null,
	presenceofcyclelane_indirectionsegregated_m numeric(6,2) not null,
	presenceofcyclelane_indirectionpercentage integer not null,
	presenceofcyclelane_inoppositedirection_m numeric(6,2) not null,
	presenceofcyclelane_inoppositedirectionsegregated_m numeric(6,2) not null,
	presenceofcyclelane_inoppositedirectionpercentage integer not null,
	presenceofcyclelane_evidencedate date not null,
	presenceofcyclelane_updatedate date not null,
	presenceofcyclelane_capturemethod nvarchar(25) not null,
	PRIMARY KEY (osid)
);
