/* This DDL is based on data schema version 1.1 */
CREATE TABLE ASU_NIPCD_POSTCODEUNITPOINT (
	POSTCODE VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(50) not null,
	POSTCODENOSPACE VARCHAR2(7) not null,
	POSTCODEAREA VARCHAR2(2) not null,
	POSTCODEDISTRICT VARCHAR2(4) not null,
	POSTCODESECTOR VARCHAR2(6) not null,
	POSTCODETYPE VARCHAR2(10) not null,
	POSTCODEDELIVERYPOINTCOUNT_TOTAL NUMBER(3),
	POSTCODEDELIVERYPOINTCOUNT_RESIDENTIAL NUMBER(3),
	POSTCODEDELIVERYPOINTCOUNT_COMMERCIAL NUMBER(3),
	POSTCODEDELIVERYPOINTCOUNT_MATCHED NUMBER(3),
	POSTCODEDELIVERYPOINTCOUNT_UNMATCHED NUMBER(3),
	ISPOBOX VARCHAR2(20),
	INPUTADDRESSACCURACY VARCHAR2(100) not null,
	EASTING NUMERIC(8,2) not null,
	NORTHING NUMERIC(9,2) not null,
	LATITUDE NUMERIC(9,7) not null,
	LONGITUDE NUMERIC(9,7) not null,
	PRIMARY KEY (POSTCODE)
);
CREATE TABLE ASU_NIPCD_POSTCODEUNITPOINT_RLTENTY (
	RELATEDENTITYID VARCHAR2(36) not null,
	FEATURETYPEID VARCHAR2(36) not null,
	FEATURETYPEVERSIONDATE DATE not null,
	CROSSREFERENCEFEATURE VARCHAR2(50) not null,
	CROSSREFERENCEID VARCHAR2(36) not null,
	RELATIONSHIPTYPE VARCHAR2(30) not null,
	PRIMARY KEY (RELATEDENTITYID,FEATURETYPEVERSIONDATE)
);
