CREATE TABLE asu_bdy_boundaryhighwatermark (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	boundarytype VARCHAR2(50) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_ceremonialcounty (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_country (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_devolvedparliamentconstituency (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference_id VARCHAR2(50) not null,
	boundaryparentreference_featuretype VARCHAR2(50) not null,
	boundaryparentreference_classification VARCHAR2(50) not null,
	boundaryparentreference_name1_text VARCHAR2(254) not null,
	boundaryparentreference_name1_language VARCHAR2(3),
	boundaryparentreference_name2_text VARCHAR2(254),
	boundaryparentreference_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_devolvedparliamentelectoralregion (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_electoraldivision (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference1_id VARCHAR2(50) not null,
	boundaryparentreference1_featuretype VARCHAR2(50) not null,
	boundaryparentreference1_classification VARCHAR2(50) not null,
	boundaryparentreference1_name1_text VARCHAR2(254) not null,
	boundaryparentreference1_name1_language VARCHAR2(3),
	boundaryparentreference1_name2_text VARCHAR2(254),
	boundaryparentreference1_name2_language VARCHAR2(3),
	boundaryparentreference2_id VARCHAR2(3),
	boundaryparentreference2_featuretype VARCHAR2(50),
	boundaryparentreference2_classification VARCHAR2(50),
	boundaryparentreference2_name1_text VARCHAR2(254),
	boundaryparentreference2_name1_language VARCHAR2(3),
	boundaryparentreference2_name2_text VARCHAR2(254),
	boundaryparentreference2_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	hasdetachedpart NUMBER(1) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_glaassemblyconstituency (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference_id VARCHAR2(50) not null,
	boundaryparentreference_featuretype VARCHAR2(50) not null,
	boundaryparentreference_classification VARCHAR2(50) not null,
	boundaryparentreference_name1_text VARCHAR2(254) not null,
	boundaryparentreference_name1_language VARCHAR2(3),
	boundaryparentreference_name2_text VARCHAR2(254),
	boundaryparentreference_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_historiccounty (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_historiceuropeanregion (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_lowertierlocalauthority (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference_id VARCHAR2(50),
	boundaryparentreference_featuretype VARCHAR2(50),
	boundaryparentreference_classification VARCHAR2(50),
	boundaryparentreference_name1_text VARCHAR2(254),
	boundaryparentreference_name1_language VARCHAR2(3),
	boundaryparentreference_name2_text VARCHAR2(254),
	boundaryparentreference_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	isborough NUMBER(1) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_parishorcommunity (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254),
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference1_id VARCHAR2(50) not null,
	boundaryparentreference1_featuretype VARCHAR2(50) not null,
	boundaryparentreference1_classification VARCHAR2(50) not null,
	boundaryparentreference1_name1_text VARCHAR2(254) not null,
	boundaryparentreference1_name1_language VARCHAR2(3),
	boundaryparentreference1_name2_text VARCHAR2(254),
	boundaryparentreference1_name2_language VARCHAR2(3),
	boundaryparentreference2_id VARCHAR2(3),
	boundaryparentreference2_featuretype VARCHAR2(50),
	boundaryparentreference2_classification VARCHAR2(50),
	boundaryparentreference2_name1_text VARCHAR2(254),
	boundaryparentreference2_name1_language VARCHAR2(3),
	boundaryparentreference2_name2_text VARCHAR2(254),
	boundaryparentreference2_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	hassharedarea NUMBER(1) not null,
	hasdetachedpart NUMBER(1) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_pollingdistrict (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	pollingdistrictid VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference1_id VARCHAR2(50) not null,
	boundaryparentreference1_featuretype VARCHAR2(50) not null,
	boundaryparentreference1_classification VARCHAR2(50) not null,
	boundaryparentreference1_name1_text VARCHAR2(254) not null,
	boundaryparentreference1_name1_language VARCHAR2(3),
	boundaryparentreference1_name2_text VARCHAR2(254),
	boundaryparentreference1_name2_language VARCHAR2(3),
	boundaryparentreference2_id VARCHAR2(3) not null,
	boundaryparentreference2_featuretype VARCHAR2(50) not null,
	boundaryparentreference2_classification VARCHAR2(50) not null,
	boundaryparentreference2_name1_text VARCHAR2(254) not null,
	boundaryparentreference2_name1_language VARCHAR2(3),
	boundaryparentreference2_name2_text VARCHAR2(254),
	boundaryparentreference2_name2_language VARCHAR2(3),
	boundaryparentreference3_id VARCHAR2(3) not null,
	boundaryparentreference3_featuretype VARCHAR2(50) not null,
	boundaryparentreference3_classification VARCHAR2(50) not null,
	boundaryparentreference3_name1_text VARCHAR2(254) not null,
	boundaryparentreference3_name1_language VARCHAR2(3),
	boundaryparentreference3_name2_text VARCHAR2(254),
	boundaryparentreference3_name2_language VARCHAR2(3),
	boundaryparentreference4_id VARCHAR2(3),
	boundaryparentreference4_featuretype VARCHAR2(50),
	boundaryparentreference4_classification VARCHAR2(50),
	boundaryparentreference4_name1_text VARCHAR2(254),
	boundaryparentreference4_name1_language VARCHAR2(3),
	boundaryparentreference4_name2_text VARCHAR2(254),
	boundaryparentreference4_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_region (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_regionalauthority (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_uppertierlocalauthority (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	isborough NUMBER(1) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_ward (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10),
	boundarytype VARCHAR2(50) not null,
	boundaryparentreference1_id VARCHAR2(50) not null,
	boundaryparentreference1_featuretype VARCHAR2(50) not null,
	boundaryparentreference1_classification VARCHAR2(50) not null,
	boundaryparentreference1_name1_text VARCHAR2(254) not null,
	boundaryparentreference1_name1_language VARCHAR2(3),
	boundaryparentreference1_name2_text VARCHAR2(254),
	boundaryparentreference1_name2_language VARCHAR2(3),
	boundaryparentreference2_id VARCHAR2(3),
	boundaryparentreference2_featuretype VARCHAR2(50),
	boundaryparentreference2_classification VARCHAR2(50),
	boundaryparentreference2_name1_text VARCHAR2(254),
	boundaryparentreference2_name1_language VARCHAR2(3),
	boundaryparentreference2_name2_text VARCHAR2(254),
	boundaryparentreference2_name2_language VARCHAR2(3),
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	hasdetachedpart NUMBER(1) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_westminsterconstituency (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	gsscode VARCHAR2(10) not null,
	boundarytype VARCHAR2(50) not null,
	landareahectares NUMERIC(15,6) not null,
	tidalareahectares NUMERIC(15,6) not null,
	totalareahectares NUMERIC(15,6) not null,
	PRIMARY KEY (osid)
);
