/* This DDL is based on data schema version 1.0 */
CREATE TABLE ASU_BDY_BOUNDARYHIGHWATERMARK (
	OSID VARCHAR2(32) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_LENGTH NUMERIC(18,6) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(50) not null,
	BOUNDARYTYPE VARCHAR2(50) not null,
	PRIMARY KEY (osid)
);
