/* This DDL is based on data schema version 1.0 */
CREATE TABLE BLD_FTS_BUILDINGACCESSLOCATION (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_EVIDENCEDATE DATE not null,
	GEOMETRY_UPDATEDATE DATE not null,
	GEOMETRY_CAPTUREMETHOD VARCHAR2(25) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(25) not null,
	ACCESS_MODE VARCHAR2(25) not null,
	ACCESS_PURPOSE VARCHAR2(15) not null,
	ACCESS_OBSTRUCTION VARCHAR2(37) not null,
	ACCESS_LEVEL VARCHAR2(20) not null,
	ACCESS_EVIDENCEDATE DATE not null,
	ACCESS_UPDATEDATE DATE not null,
	ACCESSEDBUILDINGID VARCHAR2(36),
	PRIMARY KEY (osid)
);
