/* This DDL is based on data schema version 1.0 */
CREATE TABLE BLD_FTS_BUILDING (
	OSID VARCHAR2(32) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE DATE not null,
	VERSIONAVAILABLETODATE DATE,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_AREA_M2 NUMERIC(15,3) not null,
	GEOMETRY_UPDATEDATE DATE not null,
	THEME VARCHAR2(40) not null,
	BUILDINGPARTCOUNT NUMBER(4) not null,
	ISINSITE NUMBER(1),
	PRIMARYSITEID VARCHAR2(32),
	CONTAININGSITECOUNT NUMBER(4) not null,
	ISMAINBUILDING NUMBER(1),
	MAINBUILDING_ID VARCHAR2(32),
	MAINBUILDING_UPDATEDATE DATE,
	BUILDINGUSE VARCHAR2(100),
	OSLANDUSETIERA VARCHAR2(50),
	ADDRESSCOUNT_TOTAL NUMBER(4) not null,
	ADDRESSCOUNT_RESIDENTIAL NUMBER(4) not null,
	ADDRESSCOUNT_COMMERCIAL NUMBER(4) not null,
	ADDRESSCOUNT_OTHER NUMBER(4) not null,
	BUILDINGUSE_UPDATEDATE DATE,
	CONNECTIVITY VARCHAR2(15) not null,
	CONNECTIVITYCOUNT NUMBER(4) not null,
	CONNECTIVITY_UPDATEDATE DATE,
	PRIMARY KEY (osid)
);
CREATE TABLE bld_fts_building_bldtostecrossref (
	SITEID VARCHAR2(32),
	BUILDINGID VARCHAR2(32),
	BUILDINGVERSIONDATE DATE,
	PRIMARY KEY (siteid,buildingid,buildingversiondate)
);
CREATE TABLE bld_fts_building_bldtobldprtcrossref (
	BUILDINGPARTID VARCHAR2(32),
	BUILDINGID VARCHAR2(32),
	BUILDINGVERSIONDATE DATE,
	PRIMARY KEY (buildingpartid,buildingid,buildingversiondate)
);
CREATE TABLE bld_fts_building_bldtoaddrcrossref (
	UPRN NUMBER(36),
	BUILDINGID VARCHAR2(32),
	BUILDINGVERSIONDATE DATE,
	PRIMARY KEY (uprn,buildingid,buildingversiondate)
);
