CREATE TABLE gnm_fts_namedarea (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(18,6) not null,
	geometry_evidencedate DATE,
	geometry_updatedate DATE not null,
	geometry_source VARCHAR2(50),
	theme VARCHAR2(40) not null,
	descriptiongroup VARCHAR2(25) not null,
	description VARCHAR2(50) not null,
	description_evidencedate DATE,
	description_updatedate DATE not null,
	description_source VARCHAR2(50),
	extentdefinition VARCHAR2(50) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name1_evidencedate DATE,
	name1_updatedate DATE not null,
	name1_source VARCHAR2(50),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	name2_evidencedate DATE,
	name2_updatedate DATE,
	name2_source VARCHAR2(50),
	name3_text VARCHAR2(254),
	name3_language VARCHAR2(3),
	name3_evidencedate DATE,
	name3_updatedate DATE,
	name3_source VARCHAR2(50),
	name4_text VARCHAR2(254),
	name4_language VARCHAR2(3),
	name4_evidencedate DATE,
	name4_updatedate DATE,
	name4_source VARCHAR2(50),
	sameasdbpedia VARCHAR2(100),
	sameasgeonames VARCHAR2(100),
	sameasdbobih NUMBER(5),
	height NUMERIC(6,2),
	PRIMARY KEY (osid)
);
CREATE TABLE gnm_fts_namedpoint (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	descriptiongroup VARCHAR2(25) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	name3_text VARCHAR2(254),
	name3_language VARCHAR2(3),
	name4_text VARCHAR2(254),
	name4_language VARCHAR2(3),
	boundedbyminx NUMERIC(10,3) not null,
	boundedbyminy NUMERIC(10,3) not null,
	boundedbymaxx NUMERIC(10,3) not null,
	boundedbymaxy NUMERIC(10,3) not null,
	lowertierlocalauthoritygsscode VARCHAR2(10),
	lowertierlocalauthority_name1_text VARCHAR2(254),
	lowertierlocalauthority_name1_language VARCHAR2(3),
	lowertierlocalauthority_name2_text VARCHAR2(254),
	lowertierlocalauthority_name2_language VARCHAR2(3),
	uppertierlocalauthoritygsscode VARCHAR2(10),
	uppertierlocalauthority_name1_text VARCHAR2(254),
	uppertierlocalauthority_name1_language VARCHAR2(3),
	uppertierlocalauthority_name2_text VARCHAR2(254),
	uppertierlocalauthority_name2_language VARCHAR2(3),
	regionalauthoritygsscode VARCHAR2(10),
	regionalauthority_name1_text VARCHAR2(254),
	regionalauthority_name1_language VARCHAR2(3),
	regionalauthority_name2_text VARCHAR2(254),
	regionalauthority_name2_language VARCHAR2(3),
	regiongsscode VARCHAR2(10),
	region_name1_text VARCHAR2(254),
	region_name1_language VARCHAR2(3),
	region_name2_text VARCHAR2(254),
	region_name2_language VARCHAR2(3),
	countrygsscode VARCHAR2(10),
	country_name1_text VARCHAR2(254),
	country_name1_language VARCHAR2(3),
	country_name2_text VARCHAR2(254),
	country_name2_language VARCHAR2(3),
	sameasdbpedia VARCHAR2(100),
	sameasgeonames VARCHAR2(100),
	sameasdbobih NUMBER(5),
	height NUMERIC(6,2),
	PRIMARY KEY (osid)
);
