/* This DDL is based on data schema version 1.0 */
CREATE TABLE GNM_FTS_NAMEDROADJUNCTION (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(30) not null,
	NAME1_TEXT VARCHAR2(254),
	NAME1_LANGUAGE VARCHAR2(3),
	NAME2_TEXT VARCHAR2(254),
	NAME2_LANGUAGE VARCHAR2(3),
	ROADCLASSIFICATIONNUMBER VARCHAR2(10),
	JUNCTIONNUMBER VARCHAR2(10),
	INTERSECTINGROADS1_TEXT VARCHAR2(400),
	INTERSECTINGROADS1_LANGUAGE VARCHAR2(3),
	INTERSECTINGROADS2_TEXT VARCHAR2(400),
	INTERSECTINGROADS2_LANGUAGE VARCHAR2(3),
	PRIMARY KEY (osid)
);
