/* This DDL is based on data schema version 1.0 */
CREATE TABLE GNM_FTS_CROWDSOURCEDNAMEPOINT (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(20) not null,
	NAME_TEXT VARCHAR2(100) not null,
	NAME_LANGUAGE VARCHAR2(3) not null,
	NAME_EVIDENCEDATE DATE not null,
	NAME_SOURCE VARCHAR2(100) not null,
	HASSIMILAROSNAME NUMBER(1) not null,
	MATCHTYPE VARCHAR2(60) not null,
	SOURCECLASSIFICATION VARCHAR2(200) not null,
	MATCHEDOSID VARCHAR2(36),
	MATCHEDOSID_THEME VARCHAR2(20),
	MATCHEDOSID_FEATURETYPE VARCHAR2(20),
	MATCHEDUPRN NUMBER(12),
	MATCHEDUSRN NUMBER(8),
	PRIMARY KEY (osid)
);
