/* This DDL is based on data schema version 1.0 */
CREATE TABLE LUS_FTS_SITEROUTINGPOINT (
	OSID VARCHAR2(32) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_EVIDENCEDATE DATE,
	GEOMETRY_UPDATEDATE DATE not null,
	GEOMETRY_SOURCE VARCHAR2(50),
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(15) not null,
	STARTDISTANCE NUMERIC(7,2),
	ROADLINKID VARCHAR2(15),
	PRIMARY KEY (osid)
);
