/* This DDL is based on data schema version 1.0 */
CREATE TABLE LUS_FTS_SITEACCESSLOCATION (
	OSID VARCHAR2(32) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_EVIDENCEDATE DATE,
	GEOMETRY_UPDATEDATE DATE not null,
	GEOMETRY_SOURCE VARCHAR2(50),
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(15) not null,
	ACCESSTYPE VARCHAR2(30) not null,
	ACCESSTYPE_EVIDENCEDATE DATE,
	ACCESSTYPE_UPDATEDATE DATE not null,
	ACCESSTYPE_SOURCE VARCHAR2(50),
	SITEID VARCHAR2(30) not null,
	ROUTINGPOINTID VARCHAR2(30),
	ROADNODEID VARCHAR2(30),
	PRIMARY KEY (osid)
);
