CREATE TABLE lus_fts_site (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(15,6) not null,
	geometry_evidencedate DATE,
	geometry_updatedate DATE not null,
	geometry_source VARCHAR2(50),
	theme VARCHAR2(40) not null,
	description VARCHAR2(50) not null,
	description_evidencedate DATE,
	description_updatedate DATE not null,
	description_source VARCHAR2(50),
	oslandusetiera VARCHAR2(50) not null,
	oslandusetierb VARCHAR2(166),
	oslanduse_evidencedate DATE,
	oslanduse_updatedate DATE not null,
	oslanduse_source VARCHAR2(50),
	stakeholder VARCHAR2(99),
	name1_text VARCHAR2(254),
	name1_language VARCHAR2(3),
	name1_evidencedate DATE,
	name1_updatedate DATE,
	name1_source VARCHAR2(50),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	name2_evidencedate DATE,
	name2_updatedate DATE,
	name2_source VARCHAR2(50),
	primaryuprn NUMBER(12),
	extentdefinition VARCHAR2(30) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE lus_fts_siteaccesslocation (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_evidencedate DATE,
	geometry_updatedate DATE not null,
	geometry_source VARCHAR2(50),
	theme VARCHAR2(40) not null,
	description VARCHAR2(15) not null,
	accesstype VARCHAR2(30) not null,
	accesstype_evidencedate DATE,
	accesstype_updatedate DATE not null,
	accesstype_source VARCHAR2(50),
	siteid VARCHAR2(30) not null,
	routingpointid VARCHAR2(30),
	roadnodeid VARCHAR2(30),
	PRIMARY KEY (osid)
);
CREATE TABLE lus_fts_siteroutingpoint (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_evidencedate DATE,
	geometry_updatedate DATE not null,
	geometry_source VARCHAR2(50),
	theme VARCHAR2(40) not null,
	description VARCHAR2(15) not null,
	startdistance NUMERIC(7,2),
	roadlinkid VARCHAR2(15),
	PRIMARY KEY (osid)
);
