CREATE TABLE trn_ntwk_connectinglink (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(15) not null,
	connectingnodeid VARCHAR2(15) not null,
	pathnodeid VARCHAR2(15) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_connectingnode (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(15) not null,
	roadlinkid VARCHAR2(15),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_ferrylink (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(10) not null,
	fictitious NUMBER(1),
	vehicularferry NUMBER(1) not null,
	routeoperator VARCHAR2(250),
	startnode VARCHAR2(10) not null,
	endnode VARCHAR2(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_ferrynode (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_ferryterminal (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(14) not null,
	name1_text VARCHAR2(254),
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	ferryterminalcode VARCHAR2(10),
	roadnodeid VARCHAR2(3),
	pathnodeid VARCHAR2(3),
	ferrynodeid VARCHAR2(3) not null,
	siteid VARCHAR2(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_path (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(4) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_path_pathlinkref (
	pathlinkid VARCHAR2(),
	pathid VARCHAR2(),
	pathversiondate DATE,
	PRIMARY KEY (pathlinkid,pathid,pathversiondate)
);
CREATE TABLE trn_ntwk_pathlink (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(42) not null,
	pathname1_text VARCHAR2(254),
	pathname1_language VARCHAR2(3),
	pathname2_text VARCHAR2(254),
	pathname2_language VARCHAR2(3),
	alternatename1_text VARCHAR2(254),
	alternatename1_language VARCHAR2(3),
	alternatename2_text VARCHAR2(254),
	alternatename2_language VARCHAR2(3),
	surfacetype VARCHAR2(13),
	cyclefacility VARCHAR2(45),
	cyclefacility_wholelink NUMBER(1),
	elevationgain_indirection NUMERIC(6,1) not null,
	elevationgain_againstdirection NUMERIC(6,1) not null,
	heightingmethod VARCHAR2(19) not null,
	capturespecification VARCHAR2(10) not null,
	matchstatus VARCHAR2(39) not null,
	startnode VARCHAR2(39) not null,
	startgradeseparation NUMBER(2) not null,
	endnode VARCHAR2(39) not null,
	endgradeseparation NUMBER(2) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_pathnode (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(9) not null,
	formofroadnode VARCHAR2(21) not null,
	classification VARCHAR2(21),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_road (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(4) not null,
	designatedname1_text VARCHAR2(254),
	designatedname1_language VARCHAR2(3),
	designatedname1_responsibleauthorityidentifier VARCHAR2(4),
	designatedname1_responsibleauthorityname VARCHAR2(100),
	designatedname2_text VARCHAR2(254),
	designatedname2_language VARCHAR2(3),
	designatedname2_responsibleauthorityidentifier VARCHAR2(4),
	designatedname2_responsibleauthorityname VARCHAR2(100),
	nationalroadcode VARCHAR2(10),
	roadclassification VARCHAR2(21),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_road_rdlinkref (
	roadlinkid VARCHAR2(),
	roadid VARCHAR2(),
	roadversiondate DATE,
	PRIMARY KEY (roadlinkid,roadid,roadversiondate)
);
CREATE TABLE trn_ntwk_roadjunction (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(26) not null,
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	roadclassificationnumber VARCHAR2(10),
	junctionnumber VARCHAR2(10),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadjunction_rdnoderef (
	roadnodeid VARCHAR2(),
	roadjunctionid VARCHAR2(),
	roadjunctionversiondate DATE,
	PRIMARY KEY (roadnodeid,roadjunctionid,roadjunctionversiondate)
);
CREATE TABLE trn_ntwk_roadlink (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(42) not null,
	roadclassification VARCHAR2(21) not null,
	routehierarchy VARCHAR2(32) not null,
	trunkroad NUMBER(1),
	primaryroute NUMBER(1),
	roadclassificationnumber VARCHAR2(10),
	name1_text VARCHAR2(254),
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	alternatename1_text VARCHAR2(254),
	alternatename1_language VARCHAR2(3),
	alternatename2_text VARCHAR2(254),
	alternatename2_language VARCHAR2(3),
	operationalstate VARCHAR2(19) not null,
	directionality VARCHAR2(21) not null,
	cyclefacility VARCHAR2(45),
	cyclefacility_wholelink NUMBER(1),
	roadstructure VARCHAR2(14),
	roadwidth_average NUMERIC(3,1),
	roadwidth_minimum NUMERIC(3,1),
	roadwidth_confidencelevel VARCHAR2(27),
	elevationgain_indirection NUMERIC(6,1) not null,
	elevationgain_againstdirection NUMERIC(6,1) not null,
	heightingmethod VARCHAR2(19) not null,
	capturespecification VARCHAR2(10) not null,
	matchstatus VARCHAR2(39) not null,
	startnode VARCHAR2(39) not null,
	startgradeseparation NUMBER(2),
	endnode VARCHAR2(39) not null,
	endgradeseparation NUMBER(2),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadlink_rdtrkpthref (
	roadtrackorpathid VARCHAR2(),
	roadlinkid VARCHAR2(),
	roadlinkversiondate DATE,
	PRIMARY KEY (roadtrackorpathid,roadlinkid,roadlinkversiondate)
);
CREATE TABLE trn_ntwk_roadnode (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(21) not null,
	formofroadnode VARCHAR2(21) not null,
	junctionnumber1 VARCHAR2(30),
	junctionnumber2 VARCHAR2(30),
	junctionname1_text VARCHAR2(254),
	junctionname1_language VARCHAR2(3),
	junctionname2_text VARCHAR2(254),
	junctionname2_language VARCHAR2(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadnode_rdtrkpthref (
	roadtrackorpathid VARCHAR2(),
	roadnodeid VARCHAR2(),
	roadnodeversiondate DATE,
	PRIMARY KEY (roadtrackorpathid,roadnodeid,roadnodeversiondate)
);
CREATE TABLE trn_ntwk_street (
	usrn NUMBER(8) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	geometry_source VARCHAR2(23) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(35) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	designatedname1_text VARCHAR2(254),
	designatedname1_language VARCHAR2(3),
	designatedname1_responsibleauthorityidentifier VARCHAR2(4),
	designatedname1_responsibleauthorityname VARCHAR2(100),
	designatedname2_text VARCHAR2(254),
	designatedname2_language VARCHAR2(3),
	designatedname2_responsibleauthorityidentifier VARCHAR2(4),
	designatedname2_responsibleauthorityname VARCHAR2(100),
	localname1_text VARCHAR2(254),
	localname1_language VARCHAR2(3),
	localname2_text VARCHAR2(254),
	localname2_language VARCHAR2(3),
	descriptor1_text VARCHAR2(254),
	descriptor1_language VARCHAR2(3),
	descriptor2_text VARCHAR2(254),
	descriptor2_language VARCHAR2(3),
	localroadcode VARCHAR2(120),
	nationalroadcode VARCHAR2(10),
	roadclassification VARCHAR2(21),
	operationalstate VARCHAR2(19),
	operationalstatedate DATE,
	locality1_text VARCHAR2(254),
	locality1_language VARCHAR2(3),
	locality2_text VARCHAR2(254),
	locality2_language VARCHAR2(3),
	townname1_text VARCHAR2(254),
	townname1_language VARCHAR2(3),
	townname2_text VARCHAR2(254),
	townname2_language VARCHAR2(3),
	administrativearea1_text VARCHAR2(254) not null,
	administrativearea1_language VARCHAR2(3),
	administrativearea2_text VARCHAR2(254),
	administrativearea2_language VARCHAR2(3),
	responsibleauthority_identifier VARCHAR2(4) not null,
	responsibleauthority_name VARCHAR2(100) not null,
	gsscoderole1 VARCHAR2(27),
	gsscode1 VARCHAR2(9),
	gsscoderole2 VARCHAR2(27),
	gsscode2 VARCHAR2(9),
	PRIMARY KEY (usrn)
);
CREATE TABLE trn_ntwk_street_pathlinkref (
	pathlinkid VARCHAR2(),
	usrn NUMBER(8) not null,
	streetversiondate DATE,
	PRIMARY KEY (pathlinkid,usrn,streetversiondate)
);
CREATE TABLE trn_ntwk_street_rdlinkref (
	usrn NUMBER(8) not null,
	streetversiondate DATE,
	roadlinkid VARCHAR2(),
	PRIMARY KEY (roadlinkid,usrn,streetversiondate)
);
