/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_NTWK_ROADNODE (
	OSID VARCHAR2(32) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(21) not null,
	FORMOFROADNODE VARCHAR2(21) not null,
	JUNCTIONNUMBER1 VARCHAR2(30),
	JUNCTIONNUMBER2 VARCHAR2(30),
	JUNCTIONNAME1_TEXT VARCHAR2(254),
	JUNCTIONNAME1_LANGUAGE VARCHAR2(3),
	JUNCTIONNAME2_TEXT VARCHAR2(254),
	JUNCTIONNAME2_LANGUAGE VARCHAR2(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadnode_rdtrkpthref (
	ROADTRACKORPATHID VARCHAR2(32),
	ROADNODEID VARCHAR2(32),
	ROADNODEVERSIONDATE DATE,
	PRIMARY KEY (roadtrackorpathid,roadnodeid,roadnodeversiondate)
);
