/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_NTWK_CONNECTINGNODE (
	OSID VARCHAR2(36) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(15) not null,
	ROADLINKID VARCHAR2(15),
	PRIMARY KEY (osid)
);
