/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_NTWK_TRAMONROAD (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_LENGTH_M NUMERIC(15,3) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(12) not null,
	ROADLINKID VARCHAR2(36) not null,
	PRIMARY KEY (osid)
);
