/* This DDL is based on data schema version 1.1 */
CREATE TABLE TRN_NTWK_RAILWAYLINKSET (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_LENGTH_M NUMERIC(15,3) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(20) not null,
	NAME1_TEXT VARCHAR2(254) not null,
	NAME1_LANGUAGE VARCHAR2(3),
	NAME2_TEXT VARCHAR2(254),
	NAME2_LANGUAGE VARCHAR2(3),
	NAME3_TEXT VARCHAR2(254),
	NAME3_LANGUAGE VARCHAR2(3),
	NAME4_TEXT VARCHAR2(254),
	NAME4_LANGUAGE VARCHAR2(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_railwaylinkset_ralinkref (
	RAILWAYLINKID VARCHAR2(36),
	RAILWAYLINKSETID VARCHAR2(36),
	RAILWAYLINKSETVERSIONDATE DATE,
	PRIMARY KEY (railwaylinkid,railwaylinksetid,railwaylinksetversiondate)
);
