/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_RAMI_HIGHWAYDEDICATION (
	OSID VARCHAR2(32) not null,
	AUTHORITYID VARCHAR2(25) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	EFFECTIVESTARTDATE DATE not null,
	EFFECTIVEENDDATE DATE,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_LENGTH NUMERIC(15,6) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(35) not null,
	PUBLICRIGHTOFWAY NUMBER(1) not null,
	NATIONALCYCLEROUTE NUMBER(1) not null,
	QUIETROUTE NUMBER(1),
	OBSTRUCTION NUMBER(1) not null,
	PLANNINGORDER NUMBER(1),
	WORKSPROHIBITED NUMBER(1),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_highwaydedication_hwydedntwkref (
	NETWORKREFERENCEID VARCHAR2(32),
	NETWORKFEATURETYPE VARCHAR2(9),
	HIGHWAYDEDICATIONID VARCHAR2(9),
	HIGHWAYDEDICATIONVERSIONDATE DATE,
	PRIMARY KEY (networkreferenceid,highwaydedicationid,highwaydedicationversiondate)
);
