/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_NTWK_FERRYLINK (
	OSID VARCHAR2(32) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_LENGTH NUMERIC(15,6) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(10) not null,
	FICTITIOUS NUMBER(1),
	VEHICULARFERRY NUMBER(1) not null,
	ROUTEOPERATOR VARCHAR2(250),
	STARTNODE VARCHAR2(10) not null,
	ENDNODE VARCHAR2(10) not null,
	PRIMARY KEY (osid)
);
