CREATE TABLE trn_rami_highwaydedication (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(25) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(35) not null,
	publicrightofway NUMBER(1) not null,
	nationalcycleroute NUMBER(1) not null,
	quietroute NUMBER(1),
	obstruction NUMBER(1) not null,
	planningorder NUMBER(1),
	worksprohibited NUMBER(1),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_highwaydedication_hwydedntwkref (
	networkreferenceid VARCHAR2(),
	networkfeaturetype VARCHAR2(9),
	highwaydedicationid VARCHAR2(9),
	highwaydedicationversiondate DATE,
	PRIMARY KEY (networkreferenceid,highwaydedicationid,highwaydedicationversiondate)
);
CREATE TABLE trn_rami_maintenancearea (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	maintenanceresponsibility VARCHAR2(60) not null,
	maintenanceauthority_identifier VARCHAR2(4),
	maintenanceauthority_authorityname VARCHAR2(100),
	highwayauthority_identifier VARCHAR2(4) not null,
	highwayauthority_authorityname VARCHAR2(100) not null,
	locationdescription VARCHAR2(250),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_maintenanceline (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	maintenanceresponsibility VARCHAR2(60) not null,
	maintenanceauthority_identifier VARCHAR2(4),
	maintenanceauthority_authorityname VARCHAR2(100),
	highwayauthority_identifier VARCHAR2(4) not null,
	highwayauthority_authorityname VARCHAR2(100) not null,
	locationdescription VARCHAR2(250),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_maintenancepoint (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	maintenanceresponsibility VARCHAR2(60) not null,
	maintenanceauthority_identifier VARCHAR2(4),
	maintenanceauthority_authorityname VARCHAR2(100),
	highwayauthority_identifier VARCHAR2(4) not null,
	highwayauthority_authorityname VARCHAR2(100) not null,
	locationdescription VARCHAR2(250),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementarea (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	reinstatementtype VARCHAR2(60) not null,
	locationdescription VARCHAR2(250),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementline (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	reinstatementtype VARCHAR2(60) not null,
	locationdescription VARCHAR2(250),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementpoint (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	reinstatementtype VARCHAR2(60) not null,
	locationdescription VARCHAR2(250),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(24) not null,
	restriction VARCHAR2(26) not null,
	trafficsign1 VARCHAR2(120),
	trafficsign2 VARCHAR2(120),
	"STRUCTURE" VARCHAR2(40),
	inclusion VARCHAR2(1209),
	exemption VARCHAR2(1209),
	timeinterval VARCHAR2(254),
	measure1_value NUMERIC(6,1),
	measure1_unitofmeasure VARCHAR2(4),
	measure1_sourceofmeasure VARCHAR2(10),
	measure2_value NUMERIC(6,1),
	measure2_unitofmeasure VARCHAR2(4),
	measure2_sourceofmeasure VARCHAR2(10),
	atpositionxcoordinate NUMERIC(10,3),
	atpositionycoordinate NUMERIC(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction_datetimequal (
	datetimequalifierid VARCHAR2(),
	restrictionid VARCHAR2(),
	restrictionversiondate DATE,
	nameddate VARCHAR2(9),
	startdate DATE,
	enddate DATE,
	startmonthday VARCHAR2(6),
	endmonthday VARCHAR2(6),
	namedtime VARCHAR2(17),
	starttime VARCHAR2(8),
	endtime VARCHAR2(8),
	namedperiod VARCHAR2(28),
	namedday VARCHAR2(15),
	PRIMARY KEY (datetimequalifierid,restrictionversiondate)
);
CREATE TABLE trn_rami_restriction_restrictntwkref (
	networkreferenceid VARCHAR2(),
	networkfeaturetype VARCHAR2(9),
	roadlinkdirection VARCHAR2(21),
	roadlinksequence NUMBER(2),
	restrictionid VARCHAR2(21),
	restrictionversiondate DATE,
	PRIMARY KEY (networkreferenceid,restrictionid,restrictionversiondate)
);
CREATE TABLE trn_rami_routinghazard (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(12) not null,
	hazarddescription VARCHAR2(50),
	atpositionxcoordinate NUMERIC(10,3),
	atpositionycoordinate NUMERIC(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_routinghazard_routhazntwkref (
	networkreferenceid VARCHAR2(),
	networkfeaturetype VARCHAR2(9),
	routinghazardid VARCHAR2(9),
	routinghazardversiondate DATE,
	PRIMARY KEY (networkreferenceid,routinghazardid,routinghazardversiondate)
);
CREATE TABLE trn_rami_routingstructure (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(40) not null,
	structuredescription VARCHAR2(50),
	atpositionxcoordinate NUMERIC(10,3),
	atpositionycoordinate NUMERIC(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_routingstructure_routstructntwkref (
	networkreferenceid VARCHAR2(),
	networkfeaturetype VARCHAR2(9),
	routingstructureid VARCHAR2(9),
	routingstructureversiondate DATE,
	PRIMARY KEY (networkreferenceid,routingstructureid,routingstructureversiondate)
);
CREATE TABLE trn_rami_specialdesignationarea (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_area NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	designation VARCHAR2(70) not null,
	designationdescription VARCHAR2(254),
	locationdescription VARCHAR2(250),
	timeinterval VARCHAR2(254),
	contactauthority_identifier VARCHAR2(4),
	contactauthority_authorityname VARCHAR2(100),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationarea_datetimequal (
	datetimequalifierid VARCHAR2(),
	specialdesignationid VARCHAR2(),
	specialdesignationversiondate DATE,
	nameddate VARCHAR2(9),
	startdate DATE,
	enddate DATE,
	startmonthday VARCHAR2(6),
	endmonthday VARCHAR2(6),
	namedtime VARCHAR2(17),
	starttime VARCHAR2(8),
	endtime VARCHAR2(8),
	namedperiod VARCHAR2(28),
	namedday VARCHAR2(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
CREATE TABLE trn_rami_specialdesignationline (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	designation VARCHAR2(70) not null,
	designationdescription VARCHAR2(254),
	locationdescription VARCHAR2(250),
	timeinterval VARCHAR2(254),
	contactauthority_identifier VARCHAR2(4),
	contactauthority_authorityname VARCHAR2(100),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationline_datetimequal (
	datetimequalifierid VARCHAR2(),
	specialdesignationid VARCHAR2(),
	specialdesignationversiondate DATE,
	nameddate VARCHAR2(9),
	startdate DATE,
	enddate DATE,
	startmonthday VARCHAR2(6),
	endmonthday VARCHAR2(6),
	namedtime VARCHAR2(17),
	starttime VARCHAR2(8),
	endtime VARCHAR2(8),
	namedperiod VARCHAR2(28),
	namedday VARCHAR2(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
CREATE TABLE trn_rami_specialdesignationpoint (
	osid VARCHAR2() not null,
	authorityid VARCHAR2(17) not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	effectivestartdate DATE not null,
	effectiveenddate DATE,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(20) not null,
	designation VARCHAR2(70) not null,
	designationdescription VARCHAR2(254),
	locationdescription VARCHAR2(250),
	timeinterval VARCHAR2(254),
	contactauthority_identifier VARCHAR2(4),
	contactauthority_authorityname VARCHAR2(100),
	partialreference NUMBER(1) not null,
	usrn NUMBER(8) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationpoint_datetimequal (
	datetimequalifierid VARCHAR2(),
	specialdesignationid VARCHAR2(),
	specialdesignationversiondate DATE,
	nameddate VARCHAR2(9),
	startdate DATE,
	enddate DATE,
	startmonthday VARCHAR2(6),
	endmonthday VARCHAR2(6),
	namedtime VARCHAR2(17),
	starttime VARCHAR2(8),
	endtime VARCHAR2(8),
	namedperiod VARCHAR2(28),
	namedday VARCHAR2(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
