/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_FTS_STREETLIGHT (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_EVIDENCEDATE DATE not null,
	GEOMETRY_UPDATEDATE DATE,
	GEOMETRY_CAPTUREMETHOD VARCHAR2(25) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(13) not null,
	LINKID VARCHAR2(36),
	LINKID_FEATURETYPE VARCHAR2(10),
	LINKID_CONFIDENCE VARCHAR2(25) not null,
	LINKID_EVIDENCEDATE DATE not null,
	LINKID_UPDATEDATE DATE not null,
	LINKID_CAPTUREMETHOD VARCHAR2(25) not null,
	PRIMARY KEY (osid)
);
