/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_NTWK_PATHNODE (
	OSID VARCHAR2(36) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(9) not null,
	FORMOFROADNODE VARCHAR2(21) not null,
	CLASSIFICATION VARCHAR2(21),
	PRIMARY KEY (osid)
);
