/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_NTWK_RAILWAYNODE (
	OSID VARCHAR2(32) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(25) not null,
	PRIMARY KEY (osid)
);
