/* This DDL is based on data schema version 1.0 */
CREATE TABLE TRN_RAMI_RESTRICTION (
	OSID VARCHAR2(36) not null,
	TOID VARCHAR2(20),
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_LENGTH NUMERIC(15,6) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(24) not null,
	RESTRICTION VARCHAR2(26) not null,
	TRAFFICSIGN1 VARCHAR2(120),
	TRAFFICSIGN2 VARCHAR2(120),
	"STRUCTURE" VARCHAR2(40),
	INCLUSION VARCHAR2(1209),
	EXEMPTION VARCHAR2(1209),
	TIMEINTERVAL VARCHAR2(254),
	MEASURE1_VALUE NUMERIC(6,1),
	MEASURE1_UNITOFMEASURE VARCHAR2(4),
	MEASURE1_SOURCEOFMEASURE VARCHAR2(10),
	MEASURE2_VALUE NUMERIC(6,1),
	MEASURE2_UNITOFMEASURE VARCHAR2(4),
	MEASURE2_SOURCEOFMEASURE VARCHAR2(10),
	ATPOSITIONXCOORDINATE NUMERIC(10,3),
	ATPOSITIONYCOORDINATE NUMERIC(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction_datetimequal (
	DATETIMEQUALIFIERID VARCHAR2(36),
	RESTRICTIONID VARCHAR2(36),
	RESTRICTIONVERSIONDATE DATE,
	NAMEDDATE VARCHAR2(9),
	STARTDATE DATE,
	ENDDATE DATE,
	STARTMONTHDAY VARCHAR2(6),
	ENDMONTHDAY VARCHAR2(6),
	NAMEDTIME VARCHAR2(17),
	STARTTIME VARCHAR2(8),
	ENDTIME VARCHAR2(8),
	NAMEDPERIOD VARCHAR2(28),
	NAMEDDAY VARCHAR2(15),
	PRIMARY KEY (datetimequalifierid,restrictionversiondate)
);
CREATE TABLE trn_rami_restriction_restrictntwkref (
	NETWORKREFERENCEID VARCHAR2(36),
	NETWORKFEATURETYPE VARCHAR2(9),
	ROADLINKDIRECTION VARCHAR2(21),
	ROADLINKSEQUENCE NUMBER(2),
	RESTRICTIONID VARCHAR2(21),
	RESTRICTIONVERSIONDATE DATE,
	PRIMARY KEY (networkreferenceid,restrictionid,restrictionversiondate)
);
