/* This DDL is based on data schema version 1.0 */
CREATE TABLE WTR_FTS_WATERBODYCATCHMENT (
	OSID VARCHAR2(32) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_AREA_M2 NUMERIC(15,3) not null,
	GEOMETRY_SOURCE VARCHAR2(85),
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(20) not null,
	WATERBODYID VARCHAR2(15) not null,
	WATERBODYCATEGORY VARCHAR2(20) not null,
	WATERBODYNAME_TEXT VARCHAR2(254) not null,
	WATERBODYNAME_SOURCE VARCHAR2(85),
	RIVERBASINDISTRICT_ID NUMBER(2) not null,
	RIVERBASINDISTRICT_NAME VARCHAR2(15) not null,
	INCOUNTRY VARCHAR2(16) not null,
	PRIMARY KEY (osid)
);
