/* This DDL is based on data schema version 1.0 */
CREATE TABLE WTR_FTS_RIVERBASINDISTRICTCATCHMENT (
	OSID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_AREA_M2 NUMERIC(15,3) not null,
	GEOMETRY_SOURCE VARCHAR2(85),
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(30) not null,
	RIVERBASINDISTRICTID NUMBER(2) not null,
	RIVERBASINDISTRICTNAME VARCHAR2(15) not null,
	PRIMARY KEY (osid)
);
