CREATE TABLE wtr_ntwk_waterlink (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	geometry_evidencedate DATE,
	geometry_updatedate DATE not null,
	geometry_source VARCHAR2(50),
	theme VARCHAR2(40) not null,
	description VARCHAR2(12) not null,
	description_evidencedate DATE,
	description_updatedate DATE not null,
	description_source VARCHAR2(50),
	primacy VARCHAR2(1) not null,
	watertype VARCHAR2(6) not null,
	physicallevel VARCHAR2(15) not null,
	physicalcontainment VARCHAR2(31) not null,
	flowdirection VARCHAR2(12) not null,
	permanence VARCHAR2(12) not null,
	capturespecification VARCHAR2(10),
	levelofdetail VARCHAR2(8),
	catchmentname VARCHAR2(254),
	catchmentid VARCHAR2(20),
	width NUMERIC(7,2),
	gradient NUMERIC(5,2),
	startnode VARCHAR2(8) not null,
	endnode VARCHAR2(8) not null,
	nameid VARCHAR2(8),
	name1_text VARCHAR2(254),
	name1_language VARCHAR2(3),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	namesecondaryid VARCHAR2(3),
	namesecondary1_text VARCHAR2(254),
	namesecondary1_language VARCHAR2(3),
	namesecondary2_text VARCHAR2(254),
	namesecondary2_language VARCHAR2(3),
	nametertiaryid VARCHAR2(3),
	nametertiary1_text VARCHAR2(254),
	nametertiary1_language VARCHAR2(3),
	nametertiary2_text VARCHAR2(254),
	nametertiary2_language VARCHAR2(3),
	PRIMARY KEY (osid)
);
CREATE TABLE wtr_ntwk_waterlinkset (
	osid VARCHAR2() not null,
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	geometry_length NUMERIC(15,6) not null,
	geometry_evidencedate DATE,
	geometry_updatedate DATE not null,
	geometry_source VARCHAR2(50),
	theme VARCHAR2(40) not null,
	description VARCHAR2(29) not null,
	description_evidencedate DATE,
	description_updatedate DATE not null,
	description_source VARCHAR2(50),
	name1_text VARCHAR2(254) not null,
	name1_language VARCHAR2(3),
	name1_evidencedate DATE,
	name1_updatedate DATE not null,
	name1_source VARCHAR2(50),
	name2_text VARCHAR2(254),
	name2_language VARCHAR2(3),
	name2_evidencedate DATE,
	name2_updatedate DATE,
	name2_source VARCHAR2(50),
	PRIMARY KEY (osid)
);
CREATE TABLE wtr_ntwk_waterlinkset_wtrlinkref (
	waterlinkid VARCHAR2(),
	waterlinksetid VARCHAR2(),
	waterlinksetversiondate DATE,
	PRIMARY KEY (waterlinkid,waterlinksetid,waterlinksetversiondate)
);
CREATE TABLE wtr_ntwk_waternode (
	osid VARCHAR2() not null,
	toid VARCHAR2(20),
	versiondate DATE not null,
	versionavailablefromdate TIMESTAMP not null,
	versionavailabletodate TIMESTAMP,
	changetype VARCHAR2(50) not null,
	geometry SDO_GEOMETRY not null,
	theme VARCHAR2(40) not null,
	description VARCHAR2(8) not null,
	PRIMARY KEY (osid)
);
