/* This DDL is based on data schema version 1.0 */
CREATE TABLE add_gb_royalmailaddress (
	udprn integer not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	organisationname varchar(60),
	departmentname varchar(60),
	subbuildingname varchar(30),
	buildingname varchar(50),
	buildingnumber integer,
	dependentthoroughfare varchar(80),
	thoroughfare varchar(80),
	doubledependentlocality varchar(35),
	dependentlocality varchar(35),
	posttown varchar(30) not null,
	postcode varchar(8) not null,
	postcodetype varchar(10) not null,
	deliverypointsuffix varchar(2) not null,
	welshdependentthoroughfare varchar(80),
	welshthoroughfare varchar(80),
	welshdoubledependentlocality varchar(35),
	welshdependentlocality varchar(35),
	welshposttown varchar(30),
	poboxnumber varchar(13),
	updatedate date not null,
	entrydate date not null,
	easting numeric(8,2) not null,
	northing numeric(9,2) not null,
	latitude numeric(9,7) not null,
	longitude numeric(9,7) not null,
	geometry geometry(Point, 27700) not null,
	positionalaccuracy varchar(25) not null,
	geometryallocationmethod varchar(25) not null,
	unmatchedreason varchar(100),
	unmatchedreasondate date,
	uprn bigint,
	matchedaddressfeaturetype varchar(25),
	matchtype varchar(20) not null,
	matchdate date,
	matchmethod varchar(10),
	matchingorganisation varchar(25),
	PRIMARY KEY (udprn)
);
