/* This DDL is based on data schema version 1.0 */
CREATE TABLE add_gb_streetaddress (
	usrn integer not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	streettype varchar(33) not null,
	classification varchar(26),
	operationalstate varchar(18),
	operationalstatedate date,
	streetname varchar(100) not null,
	locality varchar(35),
	townname varchar(35),
	administrativearea varchar(35) not null,
	country varchar(16) not null,
	alternatelanguagestreetname varchar(110),
	alternatelanguagelocality varchar(110),
	alternatelanguagetownname varchar(35),
	alternatelanguageadministrativearea varchar(35),
	alternatelanguage varchar(3),
	snnauthoritycode varchar(4) not null,
	snnauthoritydescription varchar(35) not null,
	surfacematerial varchar(10),
	starteasting numeric(8,2) not null,
	startnorthing numeric(9,2) not null,
	endeasting numeric(8,2) not null,
	endnorthing numeric(9,2) not null,
	startlatitude numeric(9,7) not null,
	startlongitude numeric(9,7) not null,
	endlatitude numeric(9,7) not null,
	endlongitude numeric(9,7) not null,
	geometry geometry(MultiPoint, 27700) not null,
	streettolerance integer not null,
	effectivestartdate date not null,
	effectiveenddate date,
	PRIMARY KEY (usrn)
);
