CREATE TABLE asu_bdy_boundaryhighwatermark (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	boundarytype varchar(50) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_ceremonialcounty (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_country (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_devolvedparliamentconstituency (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	boundaryparentreference_id varchar(36) not null,
	boundaryparentreference_featuretype varchar(50) not null,
	boundaryparentreference_classification varchar(50) not null,
	boundaryparentreference_name1_text varchar(254) not null,
	boundaryparentreference_name1_language varchar(3),
	boundaryparentreference_name2_text varchar(254),
	boundaryparentreference_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_devolvedparliamentelectoralregion (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_electoraldivision (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	boundaryparentreference1_id varchar(36) not null,
	boundaryparentreference1_featuretype varchar(50) not null,
	boundaryparentreference1_classification varchar(50) not null,
	boundaryparentreference1_name1_text varchar(254) not null,
	boundaryparentreference1_name1_language varchar(3),
	boundaryparentreference1_name2_text varchar(254),
	boundaryparentreference1_name2_language varchar(3),
	boundaryparentreference2_id varchar(36),
	boundaryparentreference2_featuretype varchar(50),
	boundaryparentreference2_classification varchar(50),
	boundaryparentreference2_name1_text varchar(254),
	boundaryparentreference2_name1_language varchar(3),
	boundaryparentreference2_name2_text varchar(254),
	boundaryparentreference2_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	hasdetachedpart boolean not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_glaassemblyconstituency (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	boundaryparentreference_id varchar(36) not null,
	boundaryparentreference_featuretype varchar(50) not null,
	boundaryparentreference_classification varchar(50) not null,
	boundaryparentreference_name1_text varchar(254) not null,
	boundaryparentreference_name1_language varchar(3),
	boundaryparentreference_name2_text varchar(254),
	boundaryparentreference_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_historiccounty (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_historiceuropeanregion (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_lowertierlocalauthority (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	boundaryparentreference_id varchar(36),
	boundaryparentreference_featuretype varchar(50),
	boundaryparentreference_classification varchar(50),
	boundaryparentreference_name1_text varchar(254),
	boundaryparentreference_name1_language varchar(3),
	boundaryparentreference_name2_text varchar(254),
	boundaryparentreference_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	isborough boolean not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_parishorcommunity (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254),
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	boundaryparentreference1_id varchar(36) not null,
	boundaryparentreference1_featuretype varchar(50) not null,
	boundaryparentreference1_classification varchar(50) not null,
	boundaryparentreference1_name1_text varchar(254) not null,
	boundaryparentreference1_name1_language varchar(3),
	boundaryparentreference1_name2_text varchar(254),
	boundaryparentreference1_name2_language varchar(3),
	boundaryparentreference2_id varchar(36),
	boundaryparentreference2_featuretype varchar(50),
	boundaryparentreference2_classification varchar(50),
	boundaryparentreference2_name1_text varchar(254),
	boundaryparentreference2_name1_language varchar(3),
	boundaryparentreference2_name2_text varchar(254),
	boundaryparentreference2_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	hassharedarea boolean not null,
	hasdetachedpart boolean not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_pollingdistrict (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	pollingdistrictid varchar(10) not null,
	boundarytype varchar(50) not null,
	boundaryparentreference1_id varchar(36) not null,
	boundaryparentreference1_featuretype varchar(50) not null,
	boundaryparentreference1_classification varchar(50) not null,
	boundaryparentreference1_name1_text varchar(254) not null,
	boundaryparentreference1_name1_language varchar(3),
	boundaryparentreference1_name2_text varchar(254),
	boundaryparentreference1_name2_language varchar(3),
	boundaryparentreference2_id varchar(36) not null,
	boundaryparentreference2_featuretype varchar(50) not null,
	boundaryparentreference2_classification varchar(50) not null,
	boundaryparentreference2_name1_text varchar(254) not null,
	boundaryparentreference2_name1_language varchar(3),
	boundaryparentreference2_name2_text varchar(254),
	boundaryparentreference2_name2_language varchar(3),
	boundaryparentreference3_id varchar(36) not null,
	boundaryparentreference3_featuretype varchar(50) not null,
	boundaryparentreference3_classification varchar(50) not null,
	boundaryparentreference3_name1_text varchar(254) not null,
	boundaryparentreference3_name1_language varchar(3),
	boundaryparentreference3_name2_text varchar(254),
	boundaryparentreference3_name2_language varchar(3),
	boundaryparentreference4_id varchar(36),
	boundaryparentreference4_featuretype varchar(50),
	boundaryparentreference4_classification varchar(50),
	boundaryparentreference4_name1_text varchar(254),
	boundaryparentreference4_name1_language varchar(3),
	boundaryparentreference4_name2_text varchar(254),
	boundaryparentreference4_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_region (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_regionalauthority (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_uppertierlocalauthority (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	isborough boolean not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_ward (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10),
	boundarytype varchar(50) not null,
	boundaryparentreference1_id varchar(36) not null,
	boundaryparentreference1_featuretype varchar(50) not null,
	boundaryparentreference1_classification varchar(50) not null,
	boundaryparentreference1_name1_text varchar(254) not null,
	boundaryparentreference1_name1_language varchar(3),
	boundaryparentreference1_name2_text varchar(254),
	boundaryparentreference1_name2_language varchar(3),
	boundaryparentreference2_id varchar(36),
	boundaryparentreference2_featuretype varchar(50),
	boundaryparentreference2_classification varchar(50),
	boundaryparentreference2_name1_text varchar(254),
	boundaryparentreference2_name1_language varchar(3),
	boundaryparentreference2_name2_text varchar(254),
	boundaryparentreference2_name2_language varchar(3),
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	hasdetachedpart boolean not null,
	PRIMARY KEY (osid)
);
CREATE TABLE asu_bdy_westminsterconstituency (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	gsscode varchar(10) not null,
	boundarytype varchar(50) not null,
	landareahectares numeric(15,6) not null,
	tidalareahectares numeric(15,6) not null,
	totalareahectares numeric(15,6) not null,
	PRIMARY KEY (osid)
);
