/* This DDL is based on data schema version 4.1 */
CREATE TABLE bld_fts_building (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area_m2 numeric(15,3) not null,
	geometry_updatedate date not null,
	theme varchar(40) not null,
	description varchar(45) not null,
	description_updatedate date not null,
	physicalstate varchar(20) not null,
	physicalstate_updatedate date not null,
	buildingpartcount integer not null,
	isinsite boolean not null,
	primarysiteid uuid,
	containingsitecount integer not null,
	mainbuildingid uuid,
	mainbuildingid_ismainbuilding varchar(5),
	mainbuildingid_updatedate date not null,
	buildinguse varchar(100) not null,
	buildinguse_oslandusetiera varchar(50),
	buildinguse_addresscount_total integer not null,
	buildinguse_addresscount_residential integer not null,
	buildinguse_addresscount_commercial integer not null,
	buildinguse_addresscount_other integer not null,
	buildinguse_updatedate date not null,
	connectivity varchar(15) not null,
	connectivity_count integer not null,
	connectivity_updatedate date not null,
	constructionmaterial varchar(40),
	constructionmaterial_evidencedate date,
	constructionmaterial_updatedate date,
	constructionmaterial_source varchar(85),
	constructionmaterial_capturemethod varchar(25),
	constructionmaterial_thirdpartyprovenance varchar(65),
	buildingage_period varchar(10),
	buildingage_year integer,
	buildingage_evidencedate date,
	buildingage_updatedate date,
	buildingage_source varchar(85),
	buildingage_capturemethod varchar(25),
	buildingage_thirdpartyprovenance varchar(65),
	basementpresence varchar(15),
	basementpresence_selfcontained varchar(15),
	basementpresence_evidencedate date,
	basementpresence_updatedate date,
	basementpresence_source varchar(85),
	basementpresence_capturemethod varchar(25),
	basementpresence_thirdpartyprovenance varchar(65),
	numberoffloors integer,
	numberoffloors_evidencedate date,
	numberoffloors_updatedate date,
	numberoffloors_source varchar(40),
	numberoffloors_capturemethod varchar(25),
	height_absolutemin_m numeric(5,1),
	height_absoluteroofbase_m numeric(5,1),
	height_absolutemax_m numeric(5,1),
	height_relativeroofbase_m numeric(4,1),
	height_relativemax_m numeric(4,1),
	height_confidencelevel varchar(15),
	height_evidencedate date,
	height_updatedate date,
	roofmaterial_primarymaterial varchar(35),
	roofmaterial_solarpanelpresence varchar(15),
	roofmaterial_greenroofpresence varchar(15),
	roofmaterial_confidenceindicator varchar(50),
	roofmaterial_evidencedate date,
	roofmaterial_updatedate date,
	roofmaterial_capturemethod varchar(25),
	roofshapeaspect_shape varchar(10),
	roofshapeaspect_areapitched_m2 numeric(7,1),
	roofshapeaspect_areaflat_m2 numeric(7,1),
	roofshapeaspect_areafacingnorth_m2 numeric(7,1),
	roofshapeaspect_areafacingnortheast_m2 numeric(7,1),
	roofshapeaspect_areafacingeast_m2 numeric(7,1),
	roofshapeaspect_areafacingsoutheast_m2 numeric(7,1),
	roofshapeaspect_areafacingsouth_m2 numeric(7,1),
	roofshapeaspect_areafacingsouthwest_m2 numeric(7,1),
	roofshapeaspect_areafacingwest_m2 numeric(7,1),
	roofshapeaspect_areafacingnorthwest_m2 numeric(7,1),
	roofshapeaspect_areaindeterminable_m2 numeric(7,1),
	roofshapeaspect_areatotal_m2 numeric(7,1),
	roofshapeaspect_confidenceindicator varchar(50),
	roofshapeaspect_evidencedate date,
	roofshapeaspect_updatedate date,
	roofshapeaspect_capturemethod varchar(25),
	PRIMARY KEY (osid)
);
CREATE TABLE bld_fts_building_bldtostecrossref (
	siteid uuid not null,
	buildingid uuid not null,
	buildingversiondate date not null,
	PRIMARY KEY (siteid,buildingid,buildingversiondate)
);
CREATE TABLE bld_fts_building_bldtobldprtcrossref (
	buildingpartid uuid not null,
	buildingid uuid not null,
	buildingversiondate date not null,
	PRIMARY KEY (buildingpartid,buildingid,buildingversiondate)
);
CREATE TABLE bld_fts_building_bldtoaddrcrossref (
	uprn bigint not null,
	buildingid uuid not null,
	buildingversiondate date not null,
	PRIMARY KEY (uprn,buildingid,buildingversiondate)
);
