CREATE TABLE bld_fts_buildingline (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE bld_fts_buildingpart (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	oslandcovertiera varchar(15) not null,
	oslandcovertierb varchar(20) not null,
	oslandcover_evidencedate date,
	oslandcover_updatedate date not null,
	oslandcover_source varchar(50),
	oslandusetiera varchar(50) not null,
	oslandusetierb varchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date not null,
	oslanduse_source varchar(50),
	absoluteheightroofbase numeric(6,2),
	relativeheightroofbase numeric(6,2),
	absoluteheightmaximum numeric(6,2),
	relativeheightmaximum numeric(6,2),
	absoluteheightminimum numeric(6,2),
	heightconfidencelevel varchar(15),
	height_evidencedate date,
	height_updatedate date,
	height_source varchar(50),
	associatedstructure varchar(25),
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
