/* This DDL is based on data schema version 1.0 */
CREATE TABLE gnm_fts_namedarea (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	descriptiongroup varchar(25) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	extentdefinition varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date not null,
	name1_source varchar(50),
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source varchar(50),
	name3_text varchar(254),
	name3_language varchar(3),
	name3_evidencedate date,
	name3_updatedate date,
	name3_source varchar(50),
	name4_text varchar(254),
	name4_language varchar(3),
	name4_evidencedate date,
	name4_updatedate date,
	name4_source varchar(50),
	sameasdbpedia varchar(100),
	sameasgeonames varchar(100),
	sameasdbobih integer,
	height numeric(6,2),
	PRIMARY KEY (osid)
);
