CREATE TABLE gnm_fts_namedarea (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(18,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	descriptiongroup varchar(25) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	extentdefinition varchar(50) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date not null,
	name1_source varchar(50),
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source varchar(50),
	name3_text varchar(254),
	name3_language varchar(3),
	name3_evidencedate date,
	name3_updatedate date,
	name3_source varchar(50),
	name4_text varchar(254),
	name4_language varchar(3),
	name4_evidencedate date,
	name4_updatedate date,
	name4_source varchar(50),
	sameasdbpedia varchar(100),
	sameasgeonames varchar(100),
	sameasdbobih integer,
	height numeric(6,2),
	PRIMARY KEY (osid)
);
CREATE TABLE gnm_fts_namedpoint (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Point, 27700) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	descriptiongroup varchar(25) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	name3_text varchar(254),
	name3_language varchar(3),
	name4_text varchar(254),
	name4_language varchar(3),
	boundedbyminx numeric(10,3) not null,
	boundedbyminy numeric(10,3) not null,
	boundedbymaxx numeric(10,3) not null,
	boundedbymaxy numeric(10,3) not null,
	lowertierlocalauthoritygsscode varchar(10),
	lowertierlocalauthority_name1_text varchar(254),
	lowertierlocalauthority_name1_language varchar(3),
	lowertierlocalauthority_name2_text varchar(254),
	lowertierlocalauthority_name2_language varchar(3),
	uppertierlocalauthoritygsscode varchar(10),
	uppertierlocalauthority_name1_text varchar(254),
	uppertierlocalauthority_name1_language varchar(3),
	uppertierlocalauthority_name2_text varchar(254),
	uppertierlocalauthority_name2_language varchar(3),
	regionalauthoritygsscode varchar(10),
	regionalauthority_name1_text varchar(254),
	regionalauthority_name1_language varchar(3),
	regionalauthority_name2_text varchar(254),
	regionalauthority_name2_language varchar(3),
	regiongsscode varchar(10),
	region_name1_text varchar(254),
	region_name1_language varchar(3),
	region_name2_text varchar(254),
	region_name2_language varchar(3),
	countrygsscode varchar(10),
	country_name1_text varchar(254),
	country_name1_language varchar(3),
	country_name2_text varchar(254),
	country_name2_language varchar(3),
	sameasdbpedia varchar(100),
	sameasgeonames varchar(100),
	sameasdbobih integer,
	height numeric(6,2),
	PRIMARY KEY (osid)
);
