/* This DDL is based on data schema version . */
CREATE TABLE lnd_fts_land (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(100) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	oslandcovertiera varchar(30) not null,
	oslandcovertierb varchar(120) not null,
	landform varchar(20),
	oslandcover_evidencedate date,
	oslandcover_updatedate date not null,
	oslandcover_source varchar(50),
	oslandusetiera varchar(50) not null,
	oslandusetierb varchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date not null,
	oslanduse_source varchar(50),
	istidal boolean not null,
	associatedstructure varchar(25),
	operationalstatus varchar(10),
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
