/* This DDL is based on data schema version 2.3 */
CREATE TABLE lus_fts_site (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area_m2 numeric(15,3) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_capturemethod varchar(25) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_capturemethod varchar(25) not null,
	oslandusetiera varchar(50) not null,
	oslandusetierb varchar(166),
	oslanduse_evidencedate date,
	oslanduse_updatedate date not null,
	oslanduse_capturemethod varchar(25) not null,
	stakeholder varchar(150),
	name1_text varchar(254),
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	extentdefinition varchar(30) not null,
	matcheduprn bigint,
	matcheduprn_method varchar(40),
	address_classificationcode varchar(2),
	address_primarydescription varchar(120),
	address_secondarydescription varchar(120),
	address_classificationcorrelation varchar(15),
	address_classificationsource varchar(20),
	addresscount_total integer not null,
	addresscount_residential integer not null,
	addresscount_commercial integer not null,
	addresscount_other integer not null,
	nlud_code varchar(4),
	nlud_orderdescription varchar(30),
	nlud_groupdescription varchar(40),
	mainbuildingid uuid,
	status varchar(20),
	status_updatedate date,
	PRIMARY KEY (osid)
);
CREATE TABLE lus_fts_site_siteaddressref (
	uprn bigint not null,
	siteid uuid not null,
	siteversiondate date not null,
	relationshiptype varchar(30) not null,
	PRIMARY KEY (uprn,siteid,siteversiondate,relationshiptype)
);
