/* This DDL is based on data schema version 1.0 */
CREATE TABLE str_fts_fieldboundary (
	osid uuid not null,
	structureline_osid varchar(36),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length_m numeric(15,3) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	theme varchar(40) not null,
	description varchar(15) not null,
	imagery_evidencedate date,
	minimumheight_m numeric(5,1),
	maximumheight_m numeric(5,1),
	averageheight_m numeric(5,1),
	minimumwidth_m numeric(5,1),
	maximumwidth_m numeric(5,1),
	averagewidth_m numeric(5,1),
	iswoodlandboundary boolean not null,
	iswoodlandboundary_evidencedate date not null,
	iswoodlandboundary_updatedate date,
	PRIMARY KEY (osid)
);
