/* This DDL is based on data schema version 3.0 */
CREATE TABLE str_fts_structure (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area_m2 numeric(15,3) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_capturemethod varchar(25) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_capturemethod varchar(25) not null,
	oslandcovertiera varchar(15),
	oslandcovertierb varchar(92),
	oslandcover_evidencedate date,
	oslandcover_updatedate date,
	oslandcover_capturemethod varchar(25),
	oslandusetiera varchar(50),
	oslandusetierb varchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date,
	oslanduse_capturemethod varchar(25),
	height_absoluteroofbase_m numeric(5,1),
	height_relativeroofbase_m numeric(4,1),
	height_absolutemax_m numeric(5,1),
	height_relativemax_m numeric(4,1),
	height_absolutemin_m numeric(5,1),
	height_confidencelevel varchar(15),
	height_evidencedate date,
	height_updatedate date,
	name1_text varchar(254),
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	istidal boolean not null,
	ishistoric boolean not null,
	associatedstructure varchar(25),
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	containingsitecount integer,
	smallestsite_siteid uuid,
	smallestsite_landusetiera varchar(50),
	smallestsite_landusetierb varchar(200),
	largestsite_landusetiera varchar(50),
	largestsite_landusetierb varchar(88),
	nlud_code varchar(4),
	nlud_orderdescription varchar(30),
	nlud_groupdescription varchar(40),
	address_classificationcode varchar(2),
	address_primarydescription varchar(120),
	address_secondarydescription varchar(120),
	lowertierlocalauthority_gsscode varchar(10),
	lowertierlocalauthority_count integer,
	status varchar(10),
	status_updatedate date,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structure_habcovref (
	osid uuid not null,
	scheme varchar(20) not null,
	habitatcode varchar(5),
	habitatdescription varchar(80) not null,
	percentage integer,
	percentage_evidencedate date,
	percentage_updatedate date,
	featuretypeversiondate date not null,
	PRIMARY KEY (osid,featuretypeversiondate,habitatdescription)
);
CREATE TABLE str_fts_structure_siteref (
	siteid uuid not null,
	structureid uuid not null,
	structureversiondate date not null,
	PRIMARY KEY (siteid,structureid,structureversiondate)
);
