CREATE TABLE trn_rami_highwaydedication (
	osid uuid not null,
	authorityid varchar(25) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(LineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(35) not null,
	publicrightofway boolean not null,
	nationalcycleroute boolean not null,
	quietroute boolean,
	obstruction boolean not null,
	planningorder boolean,
	worksprohibited boolean,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_highwaydedication_hwydedntwkref (
	networkreferenceid varchar(36),
	networkfeaturetype varchar(9),
	highwaydedicationid varchar(36),
	highwaydedicationversiondate date,
	PRIMARY KEY (networkreferenceid,highwaydedicationid,highwaydedicationversiondate)
);
CREATE TABLE trn_rami_maintenancearea (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	maintenanceresponsibility varchar(60) not null,
	maintenanceauthority_identifier varchar(4),
	maintenanceauthority_authorityname varchar(100),
	highwayauthority_identifier varchar(4) not null,
	highwayauthority_authorityname varchar(100) not null,
	locationdescription varchar(250),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_maintenanceline (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	maintenanceresponsibility varchar(60) not null,
	maintenanceauthority_identifier varchar(4),
	maintenanceauthority_authorityname varchar(100),
	highwayauthority_identifier varchar(4) not null,
	highwayauthority_authorityname varchar(100) not null,
	locationdescription varchar(250),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_maintenancepoint (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiPoint, 27700) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	maintenanceresponsibility varchar(60) not null,
	maintenanceauthority_identifier varchar(4),
	maintenanceauthority_authorityname varchar(100),
	highwayauthority_identifier varchar(4) not null,
	highwayauthority_authorityname varchar(100) not null,
	locationdescription varchar(250),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementarea (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	reinstatementtype varchar(60) not null,
	locationdescription varchar(250),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementline (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	reinstatementtype varchar(60) not null,
	locationdescription varchar(250),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_reinstatementpoint (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiPoint, 27700) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	reinstatementtype varchar(60) not null,
	locationdescription varchar(250),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(24) not null,
	restriction varchar(26) not null,
	trafficsign1 varchar(120),
	trafficsign2 varchar(120),
	structure varchar(40),
	inclusion varchar(1209),
	exemption varchar(1209),
	timeinterval varchar(254),
	measure1_value numeric(6,1),
	measure1_unitofmeasure varchar(4),
	measure1_sourceofmeasure varchar(10),
	measure2_value numeric(6,1),
	measure2_unitofmeasure varchar(4),
	measure2_sourceofmeasure varchar(10),
	atpositionxcoordinate numeric(10,3),
	atpositionycoordinate numeric(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_restriction_datetimequal (
	datetimequalifierid varchar(36),
	restrictionid varchar(36),
	restrictionversiondate date,
	nameddate varchar(9),
	startdate date,
	enddate date,
	startmonthday varchar(6),
	endmonthday varchar(6),
	namedtime varchar(17),
	starttime varchar(8),
	endtime varchar(8),
	namedperiod varchar(28),
	namedday varchar(15),
	PRIMARY KEY (datetimequalifierid,restrictionversiondate)
);
CREATE TABLE trn_rami_restriction_restrictntwkref (
	networkreferenceid varchar(36),
	networkfeaturetype varchar(9),
	roadlinkdirection varchar(21),
	roadlinksequence integer,
	restrictionid varchar(36),
	restrictionversiondate date,
	PRIMARY KEY (networkreferenceid,restrictionid,restrictionversiondate)
);
CREATE TABLE trn_rami_routinghazard (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(12) not null,
	hazarddescription varchar(50),
	atpositionxcoordinate numeric(10,3),
	atpositionycoordinate numeric(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_routinghazard_routhazntwkref (
	networkreferenceid varchar(36),
	networkfeaturetype varchar(9),
	routinghazardid varchar(36),
	routinghazardversiondate date,
	PRIMARY KEY (networkreferenceid,routinghazardid,routinghazardversiondate)
);
CREATE TABLE trn_rami_routingstructure (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(40) not null,
	structuredescription varchar(50),
	atpositionxcoordinate numeric(10,3),
	atpositionycoordinate numeric(10,3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_routingstructure_routstructntwkref (
	networkreferenceid varchar(36),
	networkfeaturetype varchar(9),
	routingstructureid varchar(36),
	routingstructureversiondate date,
	PRIMARY KEY (networkreferenceid,routingstructureid,routingstructureversiondate)
);
CREATE TABLE trn_rami_specialdesignationarea (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiPolygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	designation varchar(70) not null,
	designationdescription varchar(254),
	locationdescription varchar(250),
	timeinterval varchar(254),
	contactauthority_identifier varchar(4),
	contactauthority_authorityname varchar(100),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationarea_datetimequal (
	datetimequalifierid varchar(36),
	specialdesignationid varchar(36),
	specialdesignationversiondate date,
	nameddate varchar(9),
	startdate date,
	enddate date,
	startmonthday varchar(6),
	endmonthday varchar(6),
	namedtime varchar(17),
	starttime varchar(8),
	endtime varchar(8),
	namedperiod varchar(28),
	namedday varchar(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
CREATE TABLE trn_rami_specialdesignationline (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	designation varchar(70) not null,
	designationdescription varchar(254),
	locationdescription varchar(250),
	timeinterval varchar(254),
	contactauthority_identifier varchar(4),
	contactauthority_authorityname varchar(100),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationline_datetimequal (
	datetimequalifierid varchar(36),
	specialdesignationid varchar(36),
	specialdesignationversiondate date,
	nameddate varchar(9),
	startdate date,
	enddate date,
	startmonthday varchar(6),
	endmonthday varchar(6),
	namedtime varchar(17),
	starttime varchar(8),
	endtime varchar(8),
	namedperiod varchar(28),
	namedday varchar(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
CREATE TABLE trn_rami_specialdesignationpoint (
	osid uuid not null,
	authorityid varchar(17) not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	geometry geometry(MultiPoint, 27700) not null,
	theme varchar(40) not null,
	description varchar(20) not null,
	designation varchar(70) not null,
	designationdescription varchar(254),
	locationdescription varchar(250),
	timeinterval varchar(254),
	contactauthority_identifier varchar(4),
	contactauthority_authorityname varchar(100),
	partialreference boolean not null,
	usrn integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_rami_specialdesignationpoint_datetimequal (
	datetimequalifierid varchar(36),
	specialdesignationid varchar(36),
	specialdesignationversiondate date,
	nameddate varchar(9),
	startdate date,
	enddate date,
	startmonthday varchar(6),
	endmonthday varchar(6),
	namedtime varchar(17),
	starttime varchar(8),
	endtime varchar(8),
	namedperiod varchar(28),
	namedday varchar(15),
	PRIMARY KEY (datetimequalifierid,specialdesignationversiondate)
);
