/* This DDL is based on data schema version 1.0 */
CREATE TABLE trn_ntwk_street (
	usrn integer not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	geometry_source varchar(23) not null,
	theme varchar(40) not null,
	description varchar(35) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	designatedname1_text varchar(254),
	designatedname1_language varchar(3),
	designatedname1_responsibleauthorityidentifier varchar(4),
	designatedname1_responsibleauthorityname varchar(100),
	designatedname2_text varchar(254),
	designatedname2_language varchar(3),
	designatedname2_responsibleauthorityidentifier varchar(4),
	designatedname2_responsibleauthorityname varchar(100),
	localname1_text varchar(254),
	localname1_language varchar(3),
	localname2_text varchar(254),
	localname2_language varchar(3),
	descriptor1_text varchar(254),
	descriptor1_language varchar(3),
	descriptor2_text varchar(254),
	descriptor2_language varchar(3),
	localroadcode varchar(120),
	nationalroadcode varchar(10),
	roadclassification varchar(21),
	operationalstate varchar(19),
	operationalstatedate date,
	locality1_text varchar(254),
	locality1_language varchar(3),
	locality2_text varchar(254),
	locality2_language varchar(3),
	townname1_text varchar(254),
	townname1_language varchar(3),
	townname2_text varchar(254),
	townname2_language varchar(3),
	administrativearea1_text varchar(254) not null,
	administrativearea1_language varchar(3),
	administrativearea2_text varchar(254),
	administrativearea2_language varchar(3),
	responsibleauthority_identifier varchar(4) not null,
	responsibleauthority_name varchar(100) not null,
	gsscoderole1 varchar(27),
	gsscode1 varchar(9),
	gsscoderole2 varchar(27),
	gsscode2 varchar(9),
	PRIMARY KEY (usrn)
);
CREATE TABLE trn_ntwk_street_pathlinkref (
	pathlinkid uuid,
	usrn integer not null,
	streetversiondate date,
	PRIMARY KEY (pathlinkid,usrn,streetversiondate)
);
CREATE TABLE trn_ntwk_street_rdlinkref (
	usrn integer not null,
	streetversiondate date,
	roadlinkid uuid,
	PRIMARY KEY (roadlinkid,usrn,streetversiondate)
);
