CREATE TABLE trn_ntwk_connectinglink (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineStringZ, 7405) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(15) not null,
	connectingnodeid uuid not null,
	pathnodeid uuid not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_connectingnode (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(PointZ, 7405) not null,
	theme varchar(40) not null,
	description varchar(15) not null,
	roadlinkid uuid,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_ferrylink (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineStringZ, 7405) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(10) not null,
	fictitious boolean,
	vehicularferry boolean not null,
	routeoperator varchar(250),
	startnode uuid not null,
	endnode uuid not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_ferrynode (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(PointZ, 7405) not null,
	theme varchar(40) not null,
	description varchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_ferryterminal (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(Point, 27700) not null,
	theme varchar(40) not null,
	description varchar(14) not null,
	name1_text varchar(254),
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	ferryterminalcode varchar(10),
	roadnodeid uuid,
	pathnodeid uuid,
	ferrynodeid uuid not null,
	siteid uuid,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_path (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(4) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_path_pathlinkref (
	pathlinkid uuid,
	pathid uuid,
	pathversiondate date,
	PRIMARY KEY (pathlinkid,pathid,pathversiondate)
);
CREATE TABLE trn_ntwk_pathlink (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineStringZ, 7405) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(42) not null,
	pathname1_text varchar(254),
	pathname1_language varchar(3),
	pathname2_text varchar(254),
	pathname2_language varchar(3),
	alternatename1_text varchar(254),
	alternatename1_language varchar(3),
	alternatename2_text varchar(254),
	alternatename2_language varchar(3),
	surfacetype varchar(13),
	cyclefacility varchar(45),
	cyclefacility_wholelink boolean,
	elevationgain_indirection numeric(6,1) not null,
	elevationgain_againstdirection numeric(6,1) not null,
	heightingmethod varchar(19) not null,
	capturespecification varchar(10) not null,
	matchstatus varchar(39) not null,
	startnode uuid not null,
	startgradeseparation integer not null,
	endnode uuid not null,
	endgradeseparation integer not null,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_pathnode (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(PointZ, 7405) not null,
	theme varchar(40) not null,
	description varchar(9) not null,
	formofroadnode varchar(21) not null,
	classification varchar(21),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_road (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(4) not null,
	designatedname1_text varchar(254),
	designatedname1_language varchar(3),
	designatedname1_responsibleauthorityidentifier varchar(4),
	designatedname1_responsibleauthorityname varchar(100),
	designatedname2_text varchar(254),
	designatedname2_language varchar(3),
	designatedname2_responsibleauthorityidentifier varchar(4),
	designatedname2_responsibleauthorityname varchar(100),
	nationalroadcode varchar(10),
	roadclassification varchar(21),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_road_rdlinkref (
	roadlinkid uuid,
	roadid uuid,
	roadversiondate date,
	PRIMARY KEY (roadlinkid,roadid,roadversiondate)
);
CREATE TABLE trn_ntwk_roadjunction (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiPoint, 27700) not null,
	theme varchar(40) not null,
	description varchar(26) not null,
	name1_text varchar(254) not null,
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	roadclassificationnumber varchar(10),
	junctionnumber varchar(10),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadjunction_rdnoderef (
	roadnodeid uuid,
	roadjunctionid uuid,
	roadjunctionversiondate date,
	PRIMARY KEY (roadnodeid,roadjunctionid,roadjunctionversiondate)
);
CREATE TABLE trn_ntwk_roadlink (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineStringZ, 7405) not null,
	geometry_length numeric(15,6) not null,
	theme varchar(40) not null,
	description varchar(42) not null,
	roadclassification varchar(21) not null,
	routehierarchy varchar(32) not null,
	trunkroad boolean,
	primaryroute boolean,
	roadclassificationnumber varchar(10),
	name1_text varchar(254),
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	alternatename1_text varchar(254),
	alternatename1_language varchar(3),
	alternatename2_text varchar(254),
	alternatename2_language varchar(3),
	operationalstate varchar(19) not null,
	directionality varchar(21) not null,
	cyclefacility varchar(45),
	cyclefacility_wholelink boolean,
	roadstructure varchar(14),
	roadwidth_average numeric(3,1),
	roadwidth_minimum numeric(3,1),
	roadwidth_confidencelevel varchar(27),
	elevationgain_indirection numeric(6,1) not null,
	elevationgain_againstdirection numeric(6,1) not null,
	heightingmethod varchar(19) not null,
	capturespecification varchar(10) not null,
	matchstatus varchar(39) not null,
	startnode uuid not null,
	startgradeseparation integer,
	endnode uuid not null,
	endgradeseparation integer,
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadlink_rdtrkpthref (
	roadtrackorpathid uuid,
	roadlinkid uuid,
	roadlinkversiondate date,
	PRIMARY KEY (roadtrackorpathid,roadlinkid,roadlinkversiondate)
);
CREATE TABLE trn_ntwk_roadnode (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(PointZ, 7405) not null,
	theme varchar(40) not null,
	description varchar(21) not null,
	formofroadnode varchar(21) not null,
	junctionnumber1 varchar(30),
	junctionnumber2 varchar(30),
	junctionname1_text varchar(254),
	junctionname1_language varchar(3),
	junctionname2_text varchar(254),
	junctionname2_language varchar(3),
	PRIMARY KEY (osid)
);
CREATE TABLE trn_ntwk_roadnode_rdtrkpthref (
	roadtrackorpathid uuid,
	roadnodeid uuid,
	roadnodeversiondate date,
	PRIMARY KEY (roadtrackorpathid,roadnodeid,roadnodeversiondate)
);
CREATE TABLE trn_ntwk_street (
	usrn integer not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(MultiLineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	geometry_source varchar(23) not null,
	theme varchar(40) not null,
	description varchar(35) not null,
	effectivestartdate date not null,
	effectiveenddate date,
	designatedname1_text varchar(254),
	designatedname1_language varchar(3),
	designatedname1_responsibleauthorityidentifier varchar(4),
	designatedname1_responsibleauthorityname varchar(100),
	designatedname2_text varchar(254),
	designatedname2_language varchar(3),
	designatedname2_responsibleauthorityidentifier varchar(4),
	designatedname2_responsibleauthorityname varchar(100),
	localname1_text varchar(254),
	localname1_language varchar(3),
	localname2_text varchar(254),
	localname2_language varchar(3),
	descriptor1_text varchar(254),
	descriptor1_language varchar(3),
	descriptor2_text varchar(254),
	descriptor2_language varchar(3),
	localroadcode varchar(120),
	nationalroadcode varchar(10),
	roadclassification varchar(21),
	operationalstate varchar(19),
	operationalstatedate date,
	locality1_text varchar(254),
	locality1_language varchar(3),
	locality2_text varchar(254),
	locality2_language varchar(3),
	townname1_text varchar(254),
	townname1_language varchar(3),
	townname2_text varchar(254),
	townname2_language varchar(3),
	administrativearea1_text varchar(254) not null,
	administrativearea1_language varchar(3),
	administrativearea2_text varchar(254),
	administrativearea2_language varchar(3),
	responsibleauthority_identifier varchar(4) not null,
	responsibleauthority_name varchar(100) not null,
	gsscoderole1 varchar(27),
	gsscode1 varchar(9),
	gsscoderole2 varchar(27),
	gsscode2 varchar(9),
	PRIMARY KEY (usrn)
);
CREATE TABLE trn_ntwk_street_pathlinkref (
	pathlinkid uuid,
	usrn integer not null,
	streetversiondate date,
	PRIMARY KEY (pathlinkid,usrn,streetversiondate)
);
CREATE TABLE trn_ntwk_street_rdlinkref (
	usrn integer not null,
	streetversiondate date,
	roadlinkid uuid,
	PRIMARY KEY (roadlinkid,usrn,streetversiondate)
);
