/* This DDL is based on data schema version 1.0 */
CREATE TABLE trn_ntwk_railwaylink (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length_m numeric(15,3) not null,
	theme varchar(40) not null,
	description varchar(50) not null,
	gauge varchar(15),
	"structure" varchar(15),
	physicallevel varchar(15),
	railwayuse varchar(25),
	trackrepresentation varchar(15),
	direction varchar(21),
	operationalstatus varchar(10) not null,
	inferred boolean not null,
	name1_text varchar(254),
	name1_language varchar(3),
	name2_text varchar(254),
	name2_language varchar(3),
	localname1_text varchar(254),
	localname1_language varchar(3),
	localname2_text varchar(254),
	localname2_language varchar(3),
	startnode uuid not null,
	endnode uuid not null,
	PRIMARY KEY (osid)
);
