/* This DDL is based on data schema version 1.0 */
CREATE TABLE trn_ntwk_cyclelane (
	osid uuid not null,
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length_m numeric(15,3) not null,
	geometry_evidencedate date not null,
	geometry_updatedate date not null,
	geometry_capturemethod varchar(25) not null,
	theme varchar(40) not null,
	description varchar(40) not null,
	parentid varchar(36) not null,
	sideoflink varchar(10),
	cyclelaneinfo_minimumwidth_m numeric(3,1) not null,
	cyclelaneinfo_modalwidth_m numeric(3,1) not null,
	cyclelaneinfo_direction varchar(21) not null,
	cyclelaneinfo_evidencedate date not null,
	cyclelaneinfo_updatedate date not null,
	cyclelaneinfo_capturemethod varchar(25) not null,
	linkid varchar(36),
	linkid_featuretype varchar(10),
	linkid_confidence varchar(30) not null,
	linkid_evidencedate date not null,
	linkid_updatedate date not null,
	linkid_capturemethod varchar(25) not null,
	PRIMARY KEY (osid)
);
