/* This DDL is based on data schema version 3.0 */
CREATE TABLE trn_ntwk_pathlink (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	changetype varchar(50) not null,
	geometry geometry(LineStringZ, 7405) not null,
	geometry_length_m numeric(15,3) not null,
	theme varchar(40) not null,
	description varchar(42) not null,
	pathname1_text varchar(254),
	pathname1_language varchar(3),
	pathname2_text varchar(254),
	pathname2_language varchar(3),
	alternatename1_text varchar(254),
	alternatename1_language varchar(3),
	alternatename2_text varchar(254),
	alternatename2_language varchar(3),
	surfacetype varchar(13),
	elevationgain_indirection numeric(6,1) not null,
	elevationgain_againstdirection numeric(6,1) not null,
	heightingmethod varchar(19) not null,
	capturespecification varchar(10) not null,
	matchstatus varchar(39) not null,
	startnode uuid not null,
	startgradeseparation integer not null,
	endnode uuid not null,
	endgradeseparation integer not null,
	presenceofstreetlight_coverage varchar(15) not null,
	presenceofstreetlight_evidencedate date not null,
	presenceofstreetlight_updatedate date not null,
	presenceofstreetlight_capturemethod varchar(25) not null,
	presenceofcyclelane_overall_m numeric(6,2) not null,
	presenceofcyclelane_overallpercentage integer not null,
	presenceofcyclelane_indirection_m numeric(6,2) not null,
	presenceofcyclelane_indirectionsegregated_m numeric(6,2) not null,
	presenceofcyclelane_indirectionpercentage integer not null,
	presenceofcyclelane_inoppositedirection_m numeric(6,2) not null,
	presenceofcyclelane_inoppositedirectionsegregated_m numeric(6,2) not null,
	presenceofcyclelane_inoppositedirectionpercentage integer not null,
	presenceofcyclelane_evidencedate date not null,
	presenceofcyclelane_updatedate date not null,
	presenceofcyclelane_capturemethod varchar(25) not null,
	PRIMARY KEY (osid)
);
