CREATE TABLE wtr_fts_intertidalline (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	operationalstatus varchar(10) not null,
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE wtr_fts_tidalboundary (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(LineString, 27700) not null,
	geometry_length numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	watermark varchar(40) not null,
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE wtr_fts_water (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	oslandcovertiera varchar(25) not null,
	oslandcovertierb varchar(117) not null,
	oslandcover_evidencedate date,
	oslandcover_updatedate date not null,
	oslandcover_source varchar(50),
	oslandusetiera varchar(50) not null,
	oslandusetierb varchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date not null,
	oslanduse_source varchar(50),
	watertype varchar(10) not null,
	associatedstructure varchar(25),
	operationalstatus varchar(10) not null,
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE wtr_fts_waterpoint (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Point, 27700) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	name1_text varchar(254),
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name1_source varchar(50),
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source varchar(50),
	operationalstatus varchar(10) not null,
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
