/* This DDL is based on data schema version 1.0 */
CREATE TABLE str_fts_structure (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area numeric(15,6) not null,
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_source varchar(50),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_source varchar(50),
	oslandcovertiera varchar(15),
	oslandcovertierb varchar(92),
	oslandcover_evidencedate date,
	oslandcover_updatedate date,
	oslandcover_source varchar(50),
	oslandusetiera varchar(50),
	oslandusetierb varchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date,
	oslanduse_source varchar(50),
	absoluteheightroofbase numeric(6,2),
	relativeheightroofbase numeric(6,2),
	absoluteheightmaximum numeric(6,2),
	relativeheightmaximum numeric(6,2),
	absoluteheightminimum numeric(6,2),
	heightconfidencelevel varchar(15),
	height_evidencedate date,
	height_updatedate date,
	height_source varchar(50),
	name1_text varchar(254),
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name1_source varchar(50),
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	name2_source varchar(50),
	istidal boolean not null,
	ishistoric boolean not null,
	associatedstructure varchar(25),
	operationalstatus varchar(10),
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
