/* This DDL is based on data schema version 2.0 */
CREATE TABLE str_fts_structure (
	osid uuid not null,
	toid varchar(20),
	versiondate date not null,
	versionavailablefromdate timestamp not null,
	versionavailabletodate timestamp,
	firstdigitalcapturedate date,
	changetype varchar(50) not null,
	geometry geometry(Polygon, 27700) not null,
	geometry_area_m2 numeric(15,3),
	geometry_evidencedate date,
	geometry_updatedate date not null,
	geometry_capturemethod varchar(25),
	theme varchar(40) not null,
	description varchar(50) not null,
	description_evidencedate date,
	description_updatedate date not null,
	description_capturemethod varchar(25),
	oslandcovertiera varchar(15),
	oslandcovertierb varchar(92),
	oslandcover_evidencedate date,
	oslandcover_updatedate date,
	oslandcover_capturemethod varchar(25),
	oslandusetiera varchar(50),
	oslandusetierb varchar(88),
	oslanduse_evidencedate date,
	oslanduse_updatedate date,
	oslanduse_capturemethod varchar(25),
	absoluteheightroofbase numeric(6,2),
	relativeheightroofbase numeric(6,2),
	absoluteheightmaximum numeric(6,2),
	relativeheightmaximum numeric(6,2),
	absoluteheightminimum numeric(6,2),
	heightconfidencelevel varchar(15),
	height_evidencedate date,
	height_updatedate date,
	name1_text varchar(254),
	name1_language varchar(3),
	name1_evidencedate date,
	name1_updatedate date,
	name2_text varchar(254),
	name2_language varchar(3),
	name2_evidencedate date,
	name2_updatedate date,
	istidal boolean not null,
	ishistoric boolean not null,
	associatedstructure varchar(25),
	operationalstatus varchar(10),
	isobscured boolean not null,
	physicallevel varchar(15) not null,
	capturespecification varchar(10) not null,
	PRIMARY KEY (osid)
);
CREATE TABLE str_fts_structure_habcovref (
	osid uuid not null,
	scheme varchar(20),
	habitatcode varchar(5),
	habitatdescription varchar(80),
	percentage integer,
	percentage_evidencedate date,
	percentage_updatedate date,
	featuretypeversiondate date,
	PRIMARY KEY (osid,featuretypeversiondate,habitatdescription)
);
